import {
  Product,
  Category,
  Order,
  Combo,
  Coupon,
  Review,
  Banner,
  PopupSettings,
  Integration,
  StaffMember,
  RolePermission,
  ActivityLogItem,
  StoreSettings,
  MediaAsset,
} from '../_types';

export const initialSettings: StoreSettings = {
  storeName: 'AuraGlass Studio',
  storeTagline: 'Ultra-Reflective Tempered Glass Wall Art | বাংলাদেশের সেরা রিফ্লেক্টিভ গ্লাস পোস্টার',
  currency: '৳',
  announcementEnabled: true,
  announcementText:
    '⚡ Home Delivery All Over Bangladesh ✨ Just For You ✨ Most Reflective Wall Art in Bangladesh ✨ Free 3M Mounting Strips with Every Order',
  phone: '+880 1792-884422',
  email: 'support@auraglass.studio',
  address: 'Level 4, House 28, Road 11, Banani, Dhaka-1213, Bangladesh',
  freeShippingThreshold: 2500,
  insideDhakaShippingFee: 70,
  outsideDhakaShippingFee: 130,
  sessionTimeoutMinutes: 45,
};

const defaultSizeOptions = [
  { id: 'sz-sm', label: 'Small (8" x 12")', dimensions: '8" x 12" (20cm x 30cm)', price: 550, compareAtPrice: 700 },
  { id: 'sz-md', label: 'Medium (12" x 18")', dimensions: '12" x 18" (30cm x 45cm)', price: 850, compareAtPrice: 1050 },
  { id: 'sz-lg', label: 'Large (18" x 24")', dimensions: '18" x 24" (45cm x 60cm)', price: 1550, compareAtPrice: 1780 },
];

export const initialCategories: Category[] = [
  {
    id: 'cat-car',
    name: 'Car Glass Poster',
    slug: 'car-glass-poster',
    iconName: 'Car',
    image: '/demo-assets/ecommerce/demo-02/poster-porsche-gt3.jpg',
    productCount: 4,
    isVisible: true,
    order: 1,
    description: 'Precision engineered motorsport and supercar artwork printed on high-clarity 4mm tempered glass.',
  },
  {
    id: 'cat-split',
    name: 'Split Poster',
    slug: 'split-poster',
    iconName: 'Columns3',
    image: '/demo-assets/ecommerce/demo-02/poster-split-triptych.jpg',
    productCount: 2,
    isVisible: true,
    order: 2,
    description: 'Breathtaking 3-piece multi-panel panoramic triptych sets for expansive living room walls.',
  },
  {
    id: 'cat-anime',
    name: 'Anime Glass Poster',
    slug: 'anime-glass-poster',
    iconName: 'Sparkles',
    image: '/demo-assets/ecommerce/demo-02/poster-anime-cyberpunk.jpg',
    productCount: 3,
    isVisible: true,
    order: 3,
    description: 'Vivid neon and high-contrast Japanese animation legends with glowing refractive optical depth.',
  },
  {
    id: 'cat-football',
    name: 'Football Glass Poster',
    slug: 'football-glass-poster',
    iconName: 'Trophy',
    image: '/demo-assets/ecommerce/demo-02/poster-football-trophy.jpg',
    productCount: 2,
    isVisible: true,
    order: 4,
    description: 'Iconic moments of football history, World Cup glory, and sports superstars.',
  },
  {
    id: 'cat-motivational',
    name: 'Motivational Glass Poster',
    slug: 'motivational-glass-poster',
    iconName: 'TrendingUp',
    image: '/demo-assets/ecommerce/demo-02/poster-wallstreet-bull.jpg',
    productCount: 2,
    isVisible: true,
    order: 5,
    description: 'Wall Street ambition, mindset mantras, and luxury icons for corporate offices and home studios.',
  },
  {
    id: 'cat-nature',
    name: 'Nature & Cyberpunk',
    slug: 'nature-glass-poster',
    iconName: 'Mountain',
    image: '/demo-assets/ecommerce/demo-02/poster-nature-aurora.jpg',
    productCount: 2,
    isVisible: true,
    order: 6,
    description: 'Cosmic auroras, majestic misty peaks, and neon metropolitan skylines with vibrant gloss.',
  },
  {
    id: 'cat-islamic',
    name: 'Islamic Glass Poster',
    slug: 'islamic-glass-poster',
    iconName: 'Moon',
    image: '/demo-assets/ecommerce/demo-02/poster-islamic-calligraphy.jpg',
    productCount: 2,
    isVisible: true,
    order: 7,
    description: 'Timeless Quranic verses and sacred Arabic calligraphy in reflective gold on obsidian black glass.',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'ag-p1',
    name: 'Red Bull Racing Glass Poster',
    slug: 'red-bull-racing-glass-poster',
    category: 'car-glass-poster',
    categoryName: 'Car Glass Poster',
    shortBlurb: 'Red Bull Racing championship aerodynamic glass wall art with specular reflections.',
    description:
      'Elevate your space with this official-inspired Red Bull Racing glass poster. Crafted from ultra-clear 4mm diamond-cut toughened glass, it captures every curve and aerodynamic line in photographic brilliance. Features scratch resistance, lifetime color vibrancy, and damage replacement guarantee.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-F1-RB01',
    stock: 24,
    rating: 4.9,
    reviewCount: 48,
    status: 'active',
    isFeatured: true,
    badge: 'Best Seller',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-f1-redbull.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
      '/demo-assets/ecommerce/demo-02/spec-glass-feature.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1', image: '/demo-assets/ecommerce/demo-02/poster-f1-redbull.jpg' },
      { id: 'd2', label: 'Design 2', image: '/demo-assets/ecommerce/demo-02/poster-f1-ferrari.jpg' },
      { id: 'd3', label: 'Design 3', image: '/demo-assets/ecommerce/demo-02/poster-porsche-gt3.jpg' },
    ],
    finish: 'Ultra-Gloss 4mm Toughened Glass with Beveled Edges',
    mounting: 'Includes 3M Heavy-Duty No-Nail Adhesive Hanging Strips',
    specifications: {
      Material: '4mm Diamond-Polished Tempered Float Glass',
      Printing: 'Multi-layer UV Pigment Cured Sublimation',
      Durability: '100% Water, Dust & Scratch Proof',
      Mounting: '3M Command™ No-Damage Adhesive Strips (Included)',
      Origin: 'Engineered & Assembled in Dhaka, Bangladesh',
    },
    seoTitle: 'Red Bull Racing F1 Glass Poster | AuraGlass Studio',
    seoDescription: 'Premium reflective Red Bull Racing F1 glass wall art poster with lifetime color guarantee.',
  },
  {
    id: 'ag-p2',
    name: 'Porsche 911 GT3 RS Guards Red Glass Art',
    slug: 'porsche-911-gt3-rs-glass-poster',
    category: 'car-glass-poster',
    categoryName: 'Car Glass Poster',
    shortBlurb: 'Guards Red Porsche 911 GT3 RS tearing down the Nürburgring on crystal-gloss glass.',
    description:
      'Pure automotive adrenaline. The legendary Porsche 911 GT3 RS in signature Guards Red, printed with ultra-high contrast on 4mm shatter-resistant tempered glass.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-CAR-GT3RS',
    stock: 18,
    rating: 5.0,
    reviewCount: 32,
    status: 'active',
    isFeatured: true,
    badge: 'Trending',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-porsche-gt3.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1 (Track View)', image: '/demo-assets/ecommerce/demo-02/poster-porsche-gt3.jpg' },
      { id: 'd2', label: 'Design 2 (Studio Silhouette)', image: '/demo-assets/ecommerce/demo-02/poster-bmw-m4.jpg' },
    ],
    finish: 'Ultra-Gloss 4mm Toughened Glass with Beveled Edges',
    mounting: '3M Wall Mounting Tape Included',
  },
  {
    id: 'ag-p3',
    name: 'BMW M4 Competition Isle of Man Green',
    slug: 'bmw-m4-competition-glass-poster',
    category: 'car-glass-poster',
    categoryName: 'Car Glass Poster',
    shortBlurb: 'Aggressive twin-turbo M-Performance styling in mesmerizing Isle of Man metallic green.',
    description:
      'The bold kidney grille and sculpted carbon fiber hood of the BMW M4 Competition captured with radiant metallic reflection.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-CAR-M4G82',
    stock: 14,
    rating: 4.8,
    reviewCount: 19,
    status: 'active',
    isFeatured: true,
    badge: 'New Arrival',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-bmw-m4.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1', image: '/demo-assets/ecommerce/demo-02/poster-bmw-m4.jpg' },
    ],
  },
  {
    id: 'ag-p4',
    name: 'Nissan Skyline GT-R R34 Midnight Purple',
    slug: 'nissan-skyline-gtr-r34-glass-poster',
    category: 'car-glass-poster',
    categoryName: 'Car Glass Poster',
    shortBlurb: 'JDM Holy Grail Nissan Skyline R34 in shifting Midnight Purple optical pearl.',
    description:
      'The unmistakable taillights and aggressive stance of Godzilla. Printed on deep reflective float glass for unparalleled sheen in evening ambient light.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-CAR-R34GTR',
    stock: 9,
    rating: 4.9,
    reviewCount: 54,
    status: 'active',
    isFeatured: true,
    badge: 'Best Seller',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-gtr-skyline.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1', image: '/demo-assets/ecommerce/demo-02/poster-gtr-skyline.jpg' },
    ],
  },
  {
    id: 'ag-p5',
    name: 'Scuderia Ferrari SF-24 Monza Edition',
    slug: 'scuderia-ferrari-f1-glass-poster',
    category: 'car-glass-poster',
    categoryName: 'Car Glass Poster',
    shortBlurb: 'Tifosi passion captured in deep Italian Rosso Corsa on tempered glass.',
    description:
      'Ferrari Formula 1 Monza aerodynamic challenger with high-gloss mirror surface and race number highlights.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-F1-FER02',
    stock: 20,
    rating: 4.9,
    reviewCount: 27,
    status: 'active',
    isFeatured: false,
    badge: 'Trending',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-f1-ferrari.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1', image: '/demo-assets/ecommerce/demo-02/poster-f1-ferrari.jpg' },
    ],
  },
  {
    id: 'ag-p6',
    name: 'Cyberpunk Neo Tokyo Anime Glass Poster',
    slug: 'cyberpunk-neo-tokyo-glass-poster',
    category: 'anime-glass-poster',
    categoryName: 'Anime Glass Poster',
    shortBlurb: 'Breathtaking cyberpunk neon aesthetic with deep refractive ultraviolet hues.',
    description:
      'Immerse your gaming room or creative workspace in the vibrant neon glow of dystopian Tokyo. The high-gloss glass accentuates every glowing neon sign.',
    price: 1450,
    compareAtPrice: 1650,
    sku: 'AG-ANI-CYBER',
    stock: 30,
    rating: 5.0,
    reviewCount: 62,
    status: 'active',
    isFeatured: true,
    badge: 'Best Seller',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-anime-cyberpunk.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1 (Cyberpunk Girl)', image: '/demo-assets/ecommerce/demo-02/poster-anime-cyberpunk.jpg' },
      { id: 'd2', label: 'Design 2 (Neon Warrior)', image: '/demo-assets/ecommerce/demo-02/poster-anime-neon.jpg' },
    ],
  },
  {
    id: 'ag-p7',
    name: 'Electric Neon Samurai Blade Glass Art',
    slug: 'electric-neon-samurai-glass-poster',
    category: 'anime-glass-poster',
    categoryName: 'Anime Glass Poster',
    shortBlurb: 'Katana spark trail illuminated by futuristic synthwave light on dark tempered glass.',
    description:
      'Dynamic action artwork featuring laser katana sparks and cyberpunk warrior stance on deep obsidian glass.',
    price: 1450,
    compareAtPrice: 1650,
    sku: 'AG-ANI-SAMURAI',
    stock: 12,
    rating: 4.8,
    reviewCount: 23,
    status: 'active',
    isFeatured: false,
    images: [
      '/demo-assets/ecommerce/demo-02/poster-anime-neon.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1', image: '/demo-assets/ecommerce/demo-02/poster-anime-neon.jpg' },
    ],
  },
  {
    id: 'ag-p8',
    name: 'World Cup Glory Golden Champion Glass Poster',
    slug: 'world-cup-glory-champion-glass-poster',
    category: 'football-glass-poster',
    categoryName: 'Football Glass Poster',
    shortBlurb: 'The immortal moment of World Cup triumph captured with gold foil optical depth.',
    description:
      'Celebration of the greatest sporting moment. The golden trophy shines with genuine reflective warmth under room lighting.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-FTB-CHAMP',
    stock: 22,
    rating: 5.0,
    reviewCount: 79,
    status: 'active',
    isFeatured: true,
    badge: 'Best Seller',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-football-trophy.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1 (Trophy Lift)', image: '/demo-assets/ecommerce/demo-02/poster-football-trophy.jpg' },
      { id: 'd2', label: 'Design 2 (Colosseum Lights)', image: '/demo-assets/ecommerce/demo-02/poster-football-stadium.jpg' },
    ],
  },
  {
    id: 'ag-p9',
    name: 'Midnight Football Arena Under Stadium Floodlights',
    slug: 'football-arena-stadium-glass-poster',
    category: 'football-glass-poster',
    categoryName: 'Football Glass Poster',
    shortBlurb: 'Atmospheric floodlit European stadium view with dramatic fog and emerald turf.',
    description:
      'Step into the pitch atmosphere with this panoramic stadium glass piece. High-intensity floodlight flare captured with crisp clarity.',
    price: 1550,
    compareAtPrice: 1780,
    sku: 'AG-FTB-ARENA',
    stock: 16,
    rating: 4.7,
    reviewCount: 15,
    status: 'active',
    isFeatured: false,
    images: [
      '/demo-assets/ecommerce/demo-02/poster-football-stadium.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1', image: '/demo-assets/ecommerce/demo-02/poster-football-stadium.jpg' },
    ],
  },
  {
    id: 'ag-p10',
    name: 'Wall Street Charging Bull Geometric Gold',
    slug: 'wall-street-bull-geometric-gold-glass-poster',
    category: 'motivational-glass-poster',
    categoryName: 'Motivational Glass Poster',
    shortBlurb: 'Unstoppable financial power in polygonal gold geometry on obsidian black glass.',
    description:
      'The definitive statement piece for modern trading setups, executive suites, and entrepreneurs. Geometric facets in brushed gold catch ambient room light dynamically.',
    price: 1650,
    compareAtPrice: 1950,
    sku: 'AG-MOT-BULL',
    stock: 25,
    rating: 5.0,
    reviewCount: 88,
    status: 'active',
    isFeatured: true,
    badge: 'Best Seller',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-wallstreet-bull.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1 (Geometric Bull)', image: '/demo-assets/ecommerce/demo-02/poster-wallstreet-bull.jpg' },
      { id: 'd2', label: 'Design 2 (Architectural Hustle)', image: '/demo-assets/ecommerce/demo-02/poster-motivational-hustle.jpg' },
    ],
  },
  {
    id: 'ag-p11',
    name: 'Ayatul Kursi Sacred Islamic Calligraphy Gold',
    slug: 'ayatul-kursi-sacred-calligraphy-glass-poster',
    category: 'islamic-glass-poster',
    categoryName: 'Islamic Glass Poster',
    shortBlurb: 'Divine Quranic verse rendered in master Arabic thuluth script on reflective black glass.',
    description:
      'Infuse your home with peace and spiritual elegance. Ayatul Kursi calligraphed with precision in brilliant metallic gold ink on 4mm tempered glass.',
    price: 1850,
    compareAtPrice: 2200,
    sku: 'AG-ISL-AYATUL',
    stock: 35,
    rating: 5.0,
    reviewCount: 114,
    status: 'active',
    isFeatured: true,
    badge: 'Limited Edition',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-islamic-calligraphy.jpg',
      '/demo-assets/ecommerce/demo-02/poster-islamic-mosque.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: defaultSizeOptions,
    designOptions: [
      { id: 'd1', label: 'Design 1 (Brushed Gold)', image: '/demo-assets/ecommerce/demo-02/poster-islamic-calligraphy.jpg' },
      { id: 'd2', label: 'Design 2 (Sacred Mosque)', image: '/demo-assets/ecommerce/demo-02/poster-islamic-mosque.jpg' },
    ],
  },
  {
    id: 'ag-p12',
    name: 'Tokyo Neon 3-Piece Split Panel Panoramic Triptych',
    slug: 'tokyo-neon-3-piece-split-triptych',
    category: 'split-poster',
    categoryName: 'Split Poster',
    shortBlurb: 'Expansive 3-panel continuous glass wall art set spanning across 5 feet of wall space.',
    description:
      'The crown jewel of statement wall art. Three precision-cut tempered glass panels seamlessly align to form an awe-inspiring panoramic cityscape with breathtaking optical depth.',
    price: 3450,
    compareAtPrice: 4200,
    sku: 'AG-SPLIT-TOKYO',
    stock: 8,
    rating: 5.0,
    reviewCount: 38,
    status: 'active',
    isFeatured: true,
    badge: 'Limited Edition',
    images: [
      '/demo-assets/ecommerce/demo-02/poster-split-triptych.jpg',
      '/demo-assets/ecommerce/demo-02/spec-glass-feature.jpg',
      '/demo-assets/ecommerce/demo-02/size-guide-chart.jpg',
    ],
    sizeOptions: [
      { id: 'sz-triptych-std', label: 'Triptych Medium (3x 12"x24")', dimensions: '36" x 24" Combined', price: 2850, compareAtPrice: 3500 },
      { id: 'sz-triptych-lg', label: 'Triptych Large (3x 16"x32")', dimensions: '48" x 32" Combined', price: 3450, compareAtPrice: 4200 },
      { id: 'sz-triptych-xl', label: 'Triptych Master (3x 20"x40")', dimensions: '60" x 40" Combined', price: 4650, compareAtPrice: 5600 },
    ],
    designOptions: [
      { id: 'd1', label: 'Design 1 (Tokyo Neon Set)', image: '/demo-assets/ecommerce/demo-02/poster-split-triptych.jpg' },
    ],
  },
];

export const initialOrders: Order[] = [
  {
    id: 'AG-91823',
    date: '2026-09-25 18:40',
    customerName: 'Zubair Hossain',
    phone: '01712-449911',
    email: 'zubair.f1@gmail.com',
    address: 'Apartment 7A, Road 27, Block D, Banani',
    city: 'Dhaka',
    items: [
      {
        productId: 'ag-p1',
        slug: 'red-bull-racing-glass-poster',
        name: 'Red Bull Racing Glass Poster',
        price: 1550,
        quantity: 1,
        image: '/demo-assets/ecommerce/demo-02/poster-f1-redbull.jpg',
        selectedSize: 'Large (18" x 24")',
        selectedDesign: 'Design 1',
      },
      {
        productId: 'ag-p2',
        slug: 'porsche-911-gt3-rs-glass-poster',
        name: 'Porsche 911 GT3 RS Guards Red Glass Art',
        price: 1550,
        quantity: 1,
        image: '/demo-assets/ecommerce/demo-02/poster-porsche-gt3.jpg',
        selectedSize: 'Large (18" x 24")',
        selectedDesign: 'Design 1',
      },
    ],
    subtotal: 3100,
    discount: 310,
    shippingFee: 0,
    total: 2790,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    status: 'Confirmed',
    notes: 'Please ensure corner safety protectors are firmly attached before dispatch.',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-25 18:40', note: 'Customer placed order online.' },
      { status: 'Confirmed', timestamp: '2026-09-25 19:15', note: 'Order verified via phone with Zubair.' },
    ],
    fraudRisk: 'Low',
  },
  {
    id: 'AG-91812',
    date: '2026-09-25 14:10',
    customerName: 'Arafat Rahman',
    phone: '01844-332211',
    email: 'arafat.anime@yahoo.com',
    address: 'Plot 15, Sector 7, Uttara Model Town',
    city: 'Dhaka',
    items: [
      {
        productId: 'ag-p6',
        slug: 'cyberpunk-neo-tokyo-glass-poster',
        name: 'Cyberpunk Neo Tokyo Anime Glass Poster',
        price: 1450,
        quantity: 2,
        image: '/demo-assets/ecommerce/demo-02/poster-anime-cyberpunk.jpg',
        selectedSize: 'Large (18" x 24")',
        selectedDesign: 'Design 1 (Cyberpunk Girl)',
      },
    ],
    subtotal: 2900,
    discount: 0,
    shippingFee: 0,
    total: 2900,
    paymentMethod: 'bKash',
    paymentStatus: 'Paid',
    status: 'Packed',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-25 14:10', note: 'Paid via bKash TrxID: 9MK29103' },
      { status: 'Confirmed', timestamp: '2026-09-25 14:30', note: 'Payment settled.' },
      { status: 'Packed', timestamp: '2026-09-25 16:00', note: 'Bubble-wrapped in wooden crate frame.' },
    ],
    fraudRisk: 'Low',
  },
  {
    id: 'AG-91795',
    date: '2026-09-24 16:20',
    customerName: 'Nusrat Jahan',
    phone: '01911-778899',
    email: 'nusrat.jahan@outlook.com',
    address: 'House 42, Road 4, O.R. Nizam Road',
    city: 'Chittagong',
    items: [
      {
        productId: 'ag-p11',
        slug: 'ayatul-kursi-sacred-calligraphy-glass-poster',
        name: 'Ayatul Kursi Sacred Islamic Calligraphy Gold',
        price: 1850,
        quantity: 1,
        image: '/demo-assets/ecommerce/demo-02/poster-islamic-calligraphy.jpg',
        selectedSize: 'Large (18" x 24")',
        selectedDesign: 'Design 1 (Brushed Gold)',
      },
    ],
    subtotal: 1850,
    discount: 150,
    shippingFee: 130,
    total: 1830,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    status: 'Shipped',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-24 16:20', note: 'Order placed.' },
      { status: 'Confirmed', timestamp: '2026-09-24 16:50', note: 'Verified.' },
      { status: 'Packed', timestamp: '2026-09-24 19:00', note: 'Dispatched to Pathao Courier.' },
      { status: 'Shipped', timestamp: '2026-09-25 09:30', note: 'In transit to Chittagong Hub.' },
    ],
    fraudRisk: 'Low',
  },
];

export const initialCombos: Combo[] = [
  {
    id: 'cmb-motorsport',
    name: 'F1 & Supercar Duo Glass Set',
    description: 'Red Bull Racing F1 + Porsche 911 GT3 RS matching gallery wall bundle.',
    productIds: ['ag-p1', 'ag-p2'],
    originalPrice: 3100,
    discount: 500,
    finalPrice: 2600,
    isActive: true,
    image: '/demo-assets/ecommerce/demo-02/hero-banner.jpg',
  },
  {
    id: 'cmb-cyberpunk',
    name: 'Cyberpunk Neon Double Blast',
    description: 'Neo Tokyo + Electric Neon Samurai Blade matching gaming room setup.',
    productIds: ['ag-p6', 'ag-p7'],
    originalPrice: 2900,
    discount: 400,
    finalPrice: 2500,
    isActive: true,
    image: '/demo-assets/ecommerce/demo-02/poster-anime-cyberpunk.jpg',
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'cp-aura10',
    code: 'AURA10',
    discountType: 'percentage',
    discountValue: 10,
    minOrder: 1500,
    usedCount: 142,
    usageLimit: 500,
    isActive: true,
    expiresAt: '2026-12-31',
  },
  {
    id: 'cp-glass300',
    code: 'GLASS300',
    discountType: 'fixed',
    discountValue: 300,
    minOrder: 2500,
    usedCount: 78,
    usageLimit: 250,
    isActive: true,
    expiresAt: '2026-10-31',
  },
  {
    id: 'cp-freeship',
    code: 'FREESHIP',
    discountType: 'fixed',
    discountValue: 130,
    minOrder: 2000,
    usedCount: 95,
    usageLimit: 300,
    isActive: true,
    expiresAt: '2026-11-15',
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'ag-p1',
    productName: 'Red Bull Racing Glass Poster',
    customerName: 'Tanvir Hossain',
    rating: 5,
    comment:
      'The reflection and gloss quality is unreal! Hung it above my desk in Banani. Even with daylight reflections it looks like a museum display.',
    date: '2026-09-24',
    isVerified: true,
    isVisible: true,
    location: 'Dhaka',
  },
  {
    id: 'rev-2',
    productId: 'ag-p11',
    productName: 'Ayatul Kursi Sacred Islamic Calligraphy Gold',
    customerName: 'Mahtab Uddin',
    rating: 5,
    comment:
      'MashaAllah extraordinary craftsmanship. The golden calligraphy on deep black tempered glass catches room light beautifully. Very safely packed!',
    date: '2026-09-23',
    isVerified: true,
    isVisible: true,
    location: 'Chittagong',
  },
  {
    id: 'rev-3',
    productId: 'ag-p10',
    productName: 'Wall Street Charging Bull Geometric Gold',
    customerName: 'Saadman Sakib',
    rating: 5,
    comment:
      'Placed this in our startup conference room. Everyone who visits asks where we bought it. 3M mounting stickers made installation effortless without drills.',
    date: '2026-09-22',
    isVerified: true,
    isVisible: true,
    location: 'Gulshan, Dhaka',
  },
  {
    id: 'rev-4',
    productId: 'ag-p6',
    productName: 'Cyberpunk Neo Tokyo Anime Glass Poster',
    customerName: 'Faheem Rahman',
    rating: 5,
    comment:
      'Colors are super vibrant! Regular paper posters fade in 6 months, but this glass art looks forever fresh. Will order the Gojo piece next.',
    date: '2026-09-20',
    isVerified: true,
    isVisible: true,
    location: 'Sylhet',
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-hero-1',
    title: 'Transform Your Walls with Diamond-Polished Tempered Glass',
    tagline: 'ULTRA-REFLECTIVE GLASS POSTERS',
    description:
      'Unmatched optical clarity, 100% scratch-proof tempered glass, and rich luminous colors that never fade. Designed for modern luxury interiors.',
    ctaText: 'Explore Collections',
    ctaUrl: '/webapp-demo/ecommerce/demo-02/products',
    image: '/demo-assets/ecommerce/demo-02/hero-banner.jpg',
    order: 1,
    isActive: true,
    type: 'hero_main',
  },
  {
    id: 'ban-feature-1',
    title: 'Engineered for Architectural Spaces',
    tagline: 'LIFETIME DURABILITY GUARANTEE',
    description:
      '4mm shatter-resistant safety glass, laser-beveled polished corners, and 3M heavy-duty adhesive wall mounts with zero wall damage.',
    ctaText: 'Learn About Glass Quality',
    ctaUrl: '/webapp-demo/ecommerce/demo-02/products',
    image: '/demo-assets/ecommerce/demo-02/spec-glass-feature.jpg',
    order: 2,
    isActive: true,
    type: 'feature_highlight',
  },
];

export const initialPopup: PopupSettings = {
  isEnabled: true,
  badge: 'NEW COLLECTOR SPECIAL',
  headline: 'Get ৳300 OFF Your First Glass Art Piece',
  description:
    'Join over 12,000+ luxury interior enthusiasts across Bangladesh. Use code GLASS300 at checkout on orders over ৳2,500.',
  couponCode: 'GLASS300',
  ctaText: 'Claim ৳300 Voucher',
  ctaUrl: '/webapp-demo/ecommerce/demo-02/products',
  dismissText: 'No thanks, I will browse at full price',
  disclaimer: '*Applies to all car, anime, motivational and Islamic glass posters. Free 3M mounting included.',
  image: '/demo-assets/ecommerce/demo-02/poster-f1-redbull.jpg',
};

export const initialIntegrations: Integration[] = [
  {
    id: 'int-meta',
    name: 'Meta Pixel (Facebook & Instagram)',
    type: 'meta_pixel',
    placement: 'head',
    code: "fbq('init', '98127391823901'); fbq('track', 'PageView');",
    isEnabled: true,
  },
  {
    id: 'int-gtm',
    name: 'Google Tag Manager',
    type: 'gtm',
    placement: 'head',
    code: "(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});})(window,document,'script','dataLayer','GTM-AURA99');",
    isEnabled: true,
  },
  {
    id: 'int-tiktok',
    name: 'TikTok Pixel',
    type: 'tiktok_pixel',
    placement: 'head',
    code: "!function (w, d, t) { w.TiktokAnalyticsObject=t; var ttq=w[t]=w[t]||[]; }(window, document, 'ttq'); ttq.load('C1928374981'); ttq.page();",
    isEnabled: false,
  },
];

export const initialStaff: StaffMember[] = [
  {
    id: 'st-1',
    name: 'Mahir Faysal',
    email: 'mahir@auraglass.studio',
    role: 'Owner',
    status: 'active',
    lastLogin: 'Today at 21:15',
    createdAt: '2025-11-01',
  },
  {
    id: 'st-2',
    name: 'Sadia Rahman',
    email: 'sadia@auraglass.studio',
    role: 'Order Manager',
    status: 'active',
    lastLogin: 'Today at 18:30',
    createdAt: '2026-01-15',
  },
  {
    id: 'st-3',
    name: 'Imtiaz Ahmed',
    email: 'imtiaz@auraglass.studio',
    role: 'Inventory Manager',
    status: 'active',
    lastLogin: 'Yesterday at 15:40',
    createdAt: '2026-03-10',
  },
  {
    id: 'st-4',
    name: 'Tania Khan',
    email: 'tania@auraglass.studio',
    role: 'Marketing Manager',
    status: 'active',
    lastLogin: 'Sep 23, 2026',
    createdAt: '2026-05-02',
  },
];

export const initialRoles: RolePermission[] = [
  {
    id: 'role-owner',
    name: 'Owner',
    description: 'Full unrestricted merchant root authority across catalog, orders, and system settings.',
    permissions: [
      'PRODUCTS_VIEW',
      'PRODUCTS_CREATE',
      'PRODUCTS_EDIT',
      'PRODUCTS_ARCHIVE',
      'INVENTORY_VIEW',
      'INVENTORY_ADJUST',
      'ORDERS_VIEW',
      'ORDERS_EDIT',
      'ORDERS_STATUS_CHANGE',
      'ORDERS_CANCEL',
      'CATEGORIES_VIEW',
      'CATEGORIES_MANAGE',
      'BANNER_VIEW',
      'BANNER_MANAGE',
      'REVIEWS_VIEW',
      'REVIEWS_MANAGE',
      'STAFF_VIEW',
      'STAFF_MANAGE',
      'SETTINGS_VIEW',
      'SETTINGS_MANAGE',
    ],
  },
  {
    id: 'role-order',
    name: 'Order Manager',
    description: 'Order fulfillment, customer phone calls, courier delivery confirmation, and fraud check.',
    permissions: [
      'ORDERS_VIEW',
      'ORDERS_EDIT',
      'ORDERS_STATUS_CHANGE',
      'PRODUCTS_VIEW',
      'INVENTORY_VIEW',
    ],
  },
  {
    id: 'role-inventory',
    name: 'Inventory Manager',
    description: 'Stock count audits, warehouse receipts, safety glass reorder management.',
    permissions: [
      'PRODUCTS_VIEW',
      'PRODUCTS_EDIT',
      'INVENTORY_VIEW',
      'INVENTORY_ADJUST',
      'CATEGORIES_VIEW',
    ],
  },
  {
    id: 'role-marketing',
    name: 'Marketing Manager',
    description: 'Homepage promotional banners, coupon campaigns, popup promotions, and reviews.',
    permissions: [
      'BANNER_VIEW',
      'BANNER_MANAGE',
      'REVIEWS_VIEW',
      'REVIEWS_MANAGE',
      'PRODUCTS_VIEW',
      'CATEGORIES_VIEW',
    ],
  },
];

export const initialActivityLogs: ActivityLogItem[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-25 18:40:12',
    user: 'Storefront Customer',
    action: 'Order Placed',
    area: 'Orders',
    entity: 'Order #AG-91823',
    details: 'Zubair Hossain placed order for Red Bull Racing + Porsche 911 GT3 RS (Total: ৳2,790)',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-25 17:15:30',
    user: 'Sadia Rahman',
    action: 'Stock Adjusted',
    area: 'Inventory',
    entity: 'Red Bull Racing Glass Poster',
    details: 'Received +15 tempered glass sheets from glass tempering facility in Gazipur.',
  },
  {
    id: 'log-3',
    timestamp: '2026-09-25 14:10:45',
    user: 'Storefront Customer',
    action: 'Order Placed',
    area: 'Orders',
    entity: 'Order #AG-91812',
    details: 'Arafat Rahman placed order for 2x Cyberpunk Neo Tokyo (Total: ৳2,900)',
  },
  {
    id: 'log-4',
    timestamp: '2026-09-24 16:20:10',
    user: 'Mahir Faysal',
    action: 'Coupon Created',
    area: 'Coupons',
    entity: 'GLASS300',
    details: 'Created ৳300 flat discount voucher for orders above ৳2,500.',
  },
  {
    id: 'log-5',
    timestamp: '2026-09-24 11:00:22',
    user: 'Tania Khan',
    action: 'Banner Updated',
    area: 'Banners',
    entity: 'Hero Main Carousel',
    details: 'Published new luxury apartment living room showcase banner.',
  },
];

export const initialMediaAssets: MediaAsset[] = [
  {
    id: 'm1',
    name: 'hero-banner.jpg',
    url: '/demo-assets/ecommerce/demo-02/hero-banner.jpg',
    dimensions: '1920 x 1080',
    fileSize: '821 KB',
    fileType: 'image/jpeg',
    altText: 'AuraGlass luxury living room glass poster showcase',
    usageCount: 4,
    uploadedAt: '2026-09-25',
  },
  {
    id: 'm2',
    name: 'poster-f1-redbull.jpg',
    url: '/demo-assets/ecommerce/demo-02/poster-f1-redbull.jpg',
    dimensions: '1200 x 800',
    fileSize: '217 KB',
    fileType: 'image/jpeg',
    altText: 'Red Bull Racing F1 glass poster mockup on modern leather sofa',
    usageCount: 6,
    uploadedAt: '2026-09-25',
  },
  {
    id: 'm3',
    name: 'poster-porsche-gt3.jpg',
    url: '/demo-assets/ecommerce/demo-02/poster-porsche-gt3.jpg',
    dimensions: '1200 x 800',
    fileSize: '204 KB',
    fileType: 'image/jpeg',
    altText: 'Porsche 911 GT3 RS Guards Red glass wall art',
    usageCount: 5,
    uploadedAt: '2026-09-25',
  },
  {
    id: 'm4',
    name: 'poster-anime-cyberpunk.jpg',
    url: '/demo-assets/ecommerce/demo-02/poster-anime-cyberpunk.jpg',
    dimensions: '1200 x 800',
    fileSize: '166 KB',
    fileType: 'image/jpeg',
    altText: 'Cyberpunk Neo Tokyo anime glass wall art',
    usageCount: 4,
    uploadedAt: '2026-09-25',
  },
  {
    id: 'm5',
    name: 'poster-wallstreet-bull.jpg',
    url: '/demo-assets/ecommerce/demo-02/poster-wallstreet-bull.jpg',
    dimensions: '1200 x 800',
    fileSize: '74 KB',
    fileType: 'image/jpeg',
    altText: 'Wall Street Charging Bull geometric gold glass art',
    usageCount: 4,
    uploadedAt: '2026-09-25',
  },
  {
    id: 'm6',
    name: 'poster-islamic-calligraphy.jpg',
    url: '/demo-assets/ecommerce/demo-02/poster-islamic-calligraphy.jpg',
    dimensions: '1200 x 800',
    fileSize: '187 KB',
    fileType: 'image/jpeg',
    altText: 'Ayatul Kursi sacred Islamic Arabic calligraphy on glass',
    usageCount: 4,
    uploadedAt: '2026-09-25',
  },
  {
    id: 'm7',
    name: 'spec-glass-feature.jpg',
    url: '/demo-assets/ecommerce/demo-02/spec-glass-feature.jpg',
    dimensions: '1200 x 800',
    fileSize: '240 KB',
    fileType: 'image/jpeg',
    altText: '4mm diamond-cut safety glass edge and reflection',
    usageCount: 3,
    uploadedAt: '2026-09-25',
  },
];
