import { Product, Category, Vendor, Order, Coupon, Review, Article, StoreSettings } from '../_types';

export const initialSettings: StoreSettings = {
  storeName: 'Kinetic Gear',
  tagline: 'High-Performance Multi-Vendor Electronics Marketplace',
  contactEmail: 'support@kineticgear.demo',
  contactPhone: '+1 (800) 546-3842',
  address: '400 Technology Square, Suite 800, Cambridge, MA 02139',
  freeShippingThreshold: 50,
  standardShippingFee: 9.99,
  taxRatePercent: 8,
  currencySymbol: '$',
  currencyCode: 'USD',
};

export const initialCategories: Category[] = [
  {
    id: 'cat-laptops',
    slug: 'laptops',
    name: 'Laptops & Computers',
    iconName: 'laptop',
    image: '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
    itemCount: 14,
    subcategories: ['Ultrabooks', 'Creator Workstations', 'Mini PCs', 'Hardware Components'],
    featured: true,
  },
  {
    id: 'cat-smartphones',
    slug: 'smartphones',
    name: 'Smartphones & Tablets',
    iconName: 'smartphone',
    image: '/demo-assets/ecommerce/demo-03/deal-phone.jpg',
    itemCount: 18,
    subcategories: ['Flagship 5G', 'Foldable Displays', 'Rugged Handhelds', 'Stylus Tablets'],
    featured: true,
  },
  {
    id: 'cat-audio',
    slug: 'audio',
    name: 'High-Fidelity Audio',
    iconName: 'headphones',
    image: '/demo-assets/ecommerce/demo-03/prod-audio.jpg',
    itemCount: 12,
    subcategories: ['Studio Monitors', 'Wireless ANC', 'Hi-Res DACs', 'Microphones'],
    featured: true,
  },
  {
    id: 'cat-gaming',
    slug: 'gaming',
    name: 'Gaming & Esports',
    iconName: 'gamepad-2',
    image: '/demo-assets/ecommerce/demo-03/prod-gaming.jpg',
    itemCount: 16,
    subcategories: ['Pro Controllers', 'Handheld Consoles', 'Mechanical Keyboards', 'Mouse & Mats'],
    featured: true,
  },
  {
    id: 'cat-wearables',
    slug: 'wearables',
    name: 'Smart Wearables',
    iconName: 'watch',
    image: '/demo-assets/ecommerce/demo-03/deal-watch.jpg',
    itemCount: 9,
    subcategories: ['Titanium Watches', 'Fitness Bands', 'Smart Rings', 'Sports Straps'],
    featured: true,
  },
  {
    id: 'cat-power',
    slug: 'power',
    name: 'GaN Power & Charging',
    iconName: 'zap',
    image: '/demo-assets/ecommerce/demo-03/prod-power.jpg',
    itemCount: 15,
    subcategories: ['Desktop GaN Stations', 'High-Capacity Power Banks', 'Magnetic Wireless', 'Braided Cables'],
    featured: true,
  },
  {
    id: 'cat-cameras',
    slug: 'cameras',
    name: 'Drones & Cameras',
    iconName: 'camera',
    image: '/demo-assets/ecommerce/demo-03/prod-drone.jpg',
    itemCount: 8,
    subcategories: ['4K Gimbal Drones', 'Cinema Cams', 'Action Rigs', 'Lenses'],
    featured: true,
  },
  {
    id: 'cat-smart-home',
    slug: 'smart-home',
    name: 'Smart Living & Security',
    iconName: 'home',
    image: '/demo-assets/ecommerce/demo-03/prod-cam.jpg',
    itemCount: 11,
    subcategories: ['AI Security Cams', 'Smart Hubs', 'Biometric Locks', 'Ambient Lighting'],
    featured: true,
  },
  {
    id: 'cat-accessories',
    slug: 'accessories',
    name: 'Peripherals & Displays',
    iconName: 'cpu',
    image: '/demo-assets/ecommerce/demo-03/prod-monitor.jpg',
    itemCount: 20,
    subcategories: ['Curved Ultrawide', 'Ergonomic Keyboards', 'Thunderbolt Docks', 'Mounts'],
    featured: false,
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'ven-aerotech',
    slug: 'aerotech-labs',
    name: 'AeroTech Labs',
    logo: '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
    banner: '/demo-assets/ecommerce/demo-03/hero-banner.jpg',
    rating: 4.9,
    salesCount: 1420,
    priceCategory: '$$$',
    bio: 'Pioneering titanium computing hardware, ultrabooks, and low-latency creator equipment.',
    verified: true,
    status: 'Active',
    productCount: 18,
    location: 'San Francisco, CA',
  },
  {
    id: 'ven-cyberforge',
    slug: 'cyberforge-hardware',
    name: 'CyberForge Hardware',
    logo: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
    banner: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
    rating: 4.8,
    salesCount: 980,
    priceCategory: '$$',
    bio: 'Custom esports peripherals, Hall-effect magnetic controllers, and enthusiast mechanical gear.',
    verified: true,
    status: 'Active',
    productCount: 14,
    location: 'Austin, TX',
  },
  {
    id: 'ven-voltstream',
    slug: 'voltstream-dynamics',
    name: 'VoltStream Dynamics',
    logo: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
    banner: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
    rating: 4.9,
    salesCount: 2310,
    priceCategory: '$$',
    bio: 'Next-generation gallium nitride (GaN) desktop charging hubs, power banks, and battery tech.',
    verified: true,
    status: 'Active',
    productCount: 12,
    location: 'Seattle, WA',
  },
  {
    id: 'ven-audiocraft',
    slug: 'audiocraft-precision',
    name: 'AudioCraft Precision',
    logo: '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
    banner: '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
    rating: 5.0,
    salesCount: 760,
    priceCategory: '$$$',
    bio: 'Acoustic engineering studio developing reference wireless headphones and studio spatial monitors.',
    verified: true,
    status: 'Active',
    productCount: 9,
    location: 'Brooklyn, NY',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-apexbook-ultra-16',
    slug: 'apexbook-ultra-16',
    title: 'ApexBook Ultra 16 Creator Studio (M5 Pro Chip)',
    brand: 'AeroTech',
    category: 'laptops',
    subCategory: 'Ultrabooks',
    description:
      'Engineered for digital creatives, software architects, and multimedia editors. Features a 16.2-inch Liquid OLED Display (3456x2234 at 120Hz ProMotion), custom M5 Pro architecture with 12-core CPU, 18-core GPU, and 24-hour battery endurance in a unibody aerospace titanium chassis.',
    highlights: [
      'Next-Gen M5 Pro Chipset with 12-Core CPU and 18-Core GPU',
      '16.2-inch Liquid OLED 120Hz ProMotion with 1600 nits peak HDR',
      'Vapor chamber active cooling with silent mag-lev dual fans',
      'Quad Thunderbolt 5 ports with 80Gbps transfer bandwidth',
    ],
    specs: {
      Processor: 'AeroTech M5 Pro (12-Core)',
      Memory: '24GB Unified High-Speed LPDDR5X',
      Storage: '1TB NVMe PCIe 5.0 SSD (Up to 7200MB/s)',
      Display: '16.2" Liquid OLED 120Hz HDR',
      Battery: '99.8Wh Lithium-Polymer (Up to 24 Hours)',
      Weight: '1.62 kg (3.57 lbs)',
    },
    basePrice: 2899.0,
    compareAtPrice: 3199.0,
    rating: 4.9,
    reviewCount: 48,
    isFeatured: true,
    isNewArrival: true,
    isOnSale: true,
    badge: 'Sale',
    vendorId: 'ven-aerotech',
    vendorName: 'AeroTech Labs',
    vendorRating: 4.9,
    stock: 15,
    primaryImage: '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
      '/demo-assets/ecommerce/demo-03/hero-banner.jpg',
    ],
    locationCity: 'San Francisco, CA',
    variants: [
      {
        id: 'var-apex-black',
        name: 'Space Black',
        colorHex: '#18181B',
        sku: 'APX-16-BLK-24-1TB',
        price: 2899.0,
        compareAtPrice: 3199.0,
        inventory: 8,
        image: '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
      },
      {
        id: 'var-apex-silver',
        name: 'Titanium Silver',
        colorHex: '#E4E4E7',
        sku: 'APX-16-SLV-24-1TB',
        price: 2899.0,
        compareAtPrice: 3199.0,
        inventory: 7,
        image: '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
      },
    ],
  },
  {
    id: 'prod-zenith-titanium-x1',
    slug: 'zenith-titanium-x1',
    title: 'Zenith Titanium X1 Flagship 5G (Periscope Zoom)',
    brand: 'AeroTech',
    category: 'smartphones',
    subCategory: 'Flagship 5G',
    description:
      'The pinnacle of mobile imaging and computational intelligence. Crafted with Grade-5 titanium rails, a 200MP Sony LYT-900 primary sensor, 5x continuous optical periscope telephoto, and a 6.8-inch QHD+ 1-120Hz LTPO display with 4,500 nits peak outdoor brightness.',
    highlights: [
      'Grade 5 Aerospace Titanium chassis with IP68 ceramic shield',
      '200MP 1-inch sensor co-developed with German optical masters',
      'Snapdragon 8 Elite Gen 4 with dedicated AI neural engine',
      '5,800mAh silicon-carbon battery with 100W wired & 50W wireless',
    ],
    specs: {
      Display: '6.82" QHD+ LTPO AMOLED 120Hz (4,500 Nits)',
      Processor: 'Snapdragon 8 Elite Gen 4 (3nm)',
      Cameras: '200MP Main + 50MP Ultra-Wide + 50MP 5x Periscope',
      RAM: '16GB LPDDR5X',
      Storage: '512GB UFS 4.0',
      Battery: '5,800 mAh with 100W GaN Fast Charging',
    },
    basePrice: 1199.0,
    compareAtPrice: 1299.0,
    rating: 4.8,
    reviewCount: 112,
    isFeatured: true,
    isNewArrival: false,
    isOnSale: true,
    badge: 'Popular',
    vendorId: 'ven-aerotech',
    vendorName: 'AeroTech Labs',
    vendorRating: 4.9,
    stock: 28,
    primaryImage: '/demo-assets/ecommerce/demo-03/deal-phone.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/deal-phone.jpg',
      '/demo-assets/ecommerce/demo-03/prod-phone.jpg',
    ],
    locationCity: 'San Francisco, CA',
    variants: [
      {
        id: 'var-zenith-raw',
        name: 'Natural Titanium',
        colorHex: '#C5C6C7',
        sku: 'ZTH-X1-NAT-512',
        price: 1199.0,
        compareAtPrice: 1299.0,
        inventory: 14,
        image: '/demo-assets/ecommerce/demo-03/deal-phone.jpg',
      },
      {
        id: 'var-zenith-dark',
        name: 'Obsidian Black',
        colorHex: '#1F2937',
        sku: 'ZTH-X1-OBS-512',
        price: 1199.0,
        compareAtPrice: 1299.0,
        inventory: 14,
        image: '/demo-assets/ecommerce/demo-03/deal-phone.jpg',
      },
    ],
  },
  {
    id: 'prod-chrono-ultra-titanium',
    slug: 'chrono-ultra-titanium',
    title: 'Chrono Ultra Titanium Multisport GPS Smartwatch',
    brand: 'AeroTech',
    category: 'wearables',
    subCategory: 'Titanium Watches',
    description:
      'Engineered for extreme endurance, mountaineering, and precision athletics. 49mm aerospace titanium casing with raised sapphire bezel, dual-frequency multi-GNSS satellite tracking, depth gauge rated to 100m, and an ultra-vibrant 3,000 nits OLED screen with 72-hour battery life.',
    highlights: [
      '49mm Grade 5 Titanium casing with sapphire crystal lens',
      'Dual-frequency L1/L5 GPS with offline contour topographic maps',
      'Continuous ECG, blood oxygen, skin temperature, and sleep staging',
      'Water resistant to 100 meters with certified dive computer support',
    ],
    specs: {
      Case: '49mm Aerospace Titanium',
      Display: '1.99" Sapphire LTPO OLED 3000 Nits',
      Battery: '72 Hours Typical / Up to 140 Hours in Low Power',
      Sensors: 'Dual-frequency GPS, ECG, PPG Heart Rate, Depth Sensor',
      WaterResistance: '100m (EN13319 Dive Certified)',
    },
    basePrice: 799.0,
    compareAtPrice: 899.0,
    rating: 4.9,
    reviewCount: 67,
    isFeatured: true,
    isNewArrival: false,
    isOnSale: false,
    badge: 'Popular',
    vendorId: 'ven-aerotech',
    vendorName: 'AeroTech Labs',
    vendorRating: 4.9,
    stock: 22,
    primaryImage: '/demo-assets/ecommerce/demo-03/deal-watch.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/deal-watch.jpg',
      '/demo-assets/ecommerce/demo-03/prod-watch.jpg',
    ],
    locationCity: 'San Francisco, CA',
    variants: [
      {
        id: 'var-chrono-orange',
        name: 'Rescue Orange Sport Loop',
        colorHex: '#EA580C',
        sku: 'CHR-49-TI-ORG',
        price: 799.0,
        compareAtPrice: 899.0,
        inventory: 12,
        image: '/demo-assets/ecommerce/demo-03/deal-watch.jpg',
      },
      {
        id: 'var-chrono-black',
        name: 'Tactical Black Trail Band',
        colorHex: '#18181B',
        sku: 'CHR-49-TI-BLK',
        price: 799.0,
        compareAtPrice: 899.0,
        inventory: 10,
        image: '/demo-assets/ecommerce/demo-03/deal-watch.jpg',
      },
    ],
  },
  {
    id: 'prod-valkyrie-pro-controller',
    slug: 'valkyrie-pro-controller',
    title: 'Valkyrie Pro Wireless Hall-Effect Esports Controller',
    brand: 'CyberForge',
    category: 'gaming',
    subCategory: 'Pro Controllers',
    description:
      'Zero stick drift guaranteed. Equipped with contactless Hall-effect electromagnetic joysticks, mechanical micro-switch face buttons, 1,000Hz polling rate wireless connectivity, customizable trigger stops, and ergonomic textured rear paddles.',
    highlights: [
      'Electromagnetic Hall Effect Analog Sticks (No Drift)',
      'Mechanical tactile mouse-click microswitches rated for 5M clicks',
      'Ultra-low 1ms latency 2.4GHz dongle and Bluetooth 5.3',
      'Four remappable back paddles with on-the-fly macro configuration',
    ],
    specs: {
      Connectivity: '2.4GHz Wireless / Bluetooth 5.3 / USB-C Wired',
      PollingRate: '1000Hz Wireless / Wired',
      BatteryLife: 'Up to 30 Hours Continuous Play',
      Sticks: 'Contactless Hall Effect Electromagnetic',
      Compatibility: 'PC, Mac, iOS, Android, Switch',
    },
    basePrice: 169.0,
    compareAtPrice: 199.0,
    rating: 4.8,
    reviewCount: 94,
    isFeatured: true,
    isNewArrival: true,
    isOnSale: true,
    badge: 'Sale',
    vendorId: 'ven-cyberforge',
    vendorName: 'CyberForge Hardware',
    vendorRating: 4.8,
    stock: 45,
    primaryImage: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
      '/demo-assets/ecommerce/demo-03/prod-gaming.jpg',
    ],
    locationCity: 'Austin, TX',
    variants: [
      {
        id: 'var-valk-white',
        name: 'Arctic White & Cyan Glow',
        colorHex: '#F8FAFC',
        sku: 'CF-VALK-WHT',
        price: 169.0,
        compareAtPrice: 199.0,
        inventory: 25,
        image: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
      },
      {
        id: 'var-valk-black',
        name: 'Shadow Black & Stealth',
        colorHex: '#0F172A',
        sku: 'CF-VALK-BLK',
        price: 169.0,
        compareAtPrice: 199.0,
        inventory: 20,
        image: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
      },
    ],
  },
  {
    id: 'prod-soniq-studio-anc',
    slug: 'soniq-studio-anc',
    title: 'Soniq Studio Pro Spatial ANC Wireless Headphones',
    brand: 'AudioCraft',
    category: 'audio',
    subCategory: 'Wireless ANC',
    description:
      'Reference acoustic fidelity for audiophiles and sound engineers. Features custom 45mm beryllium-coated dynamic drivers, hybrid adaptive noise cancellation with 8 ambient microphones, LDAC lossless 24-bit/96kHz streaming, and memory foam lambskin earcups.',
    highlights: [
      '45mm Custom Beryllium dynamic drivers with 5Hz-45kHz response',
      'Hybrid Adaptive Noise Cancellation with real-time environment tuning',
      'Audiophile LDAC, aptX Adaptive, and AAC high-res wireless codecs',
      '55-hour battery life on a single charge with fast GaN top-up',
    ],
    specs: {
      DriverSize: '45mm Custom Beryllium Diaphragm',
      FrequencyResponse: '5Hz - 45,000Hz',
      ActiveNoiseCancellation: 'Hybrid Adaptive 42dB Attenuation',
      Codecs: 'LDAC, aptX Adaptive, AAC, SBC',
      BatteryLife: '55 Hours (ANC Off) / 42 Hours (ANC On)',
      Weight: '275g',
    },
    basePrice: 389.0,
    compareAtPrice: 449.0,
    rating: 5.0,
    reviewCount: 36,
    isFeatured: true,
    isNewArrival: false,
    isOnSale: true,
    badge: 'Popular',
    vendorId: 'ven-audiocraft',
    vendorName: 'AudioCraft Precision',
    vendorRating: 5.0,
    stock: 19,
    primaryImage: '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
      '/demo-assets/ecommerce/demo-03/prod-audio.jpg',
    ],
    locationCity: 'Brooklyn, NY',
    variants: [
      {
        id: 'var-soniq-black',
        name: 'Midnight Black & Brushed Steel',
        colorHex: '#1E1E24',
        sku: 'AC-SNQ-BLK',
        price: 389.0,
        compareAtPrice: 449.0,
        inventory: 10,
        image: '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
      },
      {
        id: 'var-soniq-silver',
        name: 'Lunar Silver & Slate',
        colorHex: '#CBD5E1',
        sku: 'AC-SNQ-SLV',
        price: 389.0,
        compareAtPrice: 449.0,
        inventory: 9,
        image: '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
      },
    ],
  },
  {
    id: 'prod-hypervolt-gan-station',
    slug: 'hypervolt-gan-station',
    title: 'HyperVolt 240W Desktop GaN Fast Charging Station',
    brand: 'VoltStream',
    category: 'power',
    subCategory: 'Desktop GaN Stations',
    description:
      'The ultimate multi-device power hub for creators. Features a transparent high-impact polycarbonate enclosure revealing internal copper induction coils, a real-time OLED wattage and temperature display, and 4 USB-C PD 3.1 ports supporting up to 140W single-port charging.',
    highlights: [
      '240W total output powered by third-gen Gallium Nitride (GaN III)',
      'OLED live screen monitoring watts, volts, amps, and thermals',
      'Dual 140W PD 3.1 USB-C ports capable of fast-charging two laptops simultaneously',
      '12-layer safety protection with active thermal monitoring',
    ],
    specs: {
      TotalOutput: '240W Max',
      Ports: '3x USB-C PD 3.1 + 1x USB-A QC 4.0',
      SinglePortMax: '140W (Port C1/C2)',
      Display: '1.4" Monochrome OLED Real-time Power Meter',
      Dimensions: '105 x 75 x 35 mm',
      Weight: '410g',
    },
    basePrice: 129.0,
    compareAtPrice: 159.0,
    rating: 4.9,
    reviewCount: 88,
    isFeatured: true,
    isSponsored: true,
    isNewArrival: false,
    isOnSale: true,
    badge: 'Hot',
    vendorId: 'ven-voltstream',
    vendorName: 'VoltStream Dynamics',
    vendorRating: 4.9,
    stock: 36,
    primaryImage: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/bento-power.jpg',
      '/demo-assets/ecommerce/demo-03/prod-power.jpg',
    ],
    locationCity: 'Seattle, WA',
    variants: [
      {
        id: 'var-volt-trans',
        name: 'Transparent Cyber Edition',
        colorHex: '#F1F5F9',
        sku: 'VS-HV240-CYB',
        price: 129.0,
        compareAtPrice: 159.0,
        inventory: 20,
        image: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
      },
      {
        id: 'var-volt-smoke',
        name: 'Smoke Gray Edition',
        colorHex: '#475569',
        sku: 'VS-HV240-SMK',
        price: 129.0,
        compareAtPrice: 159.0,
        inventory: 16,
        image: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
      },
    ],
  },
  {
    id: 'prod-omnigimbal-4k-drone',
    slug: 'omnigimbal-4k-drone',
    title: 'OmniGimbal 4K Creator Drone (Carbon Fiber)',
    brand: 'AeroTech',
    category: 'cameras',
    subCategory: '4K Gimbal Drones',
    description:
      'Ultralight 249g folding carbon fiber drone engineered for commercial videographers. Boasts a 1/1.3-inch 48MP CMOS sensor with 4K/60fps HDR, 3-axis mechanical gimbal, 360-degree omnidirectional obstacle avoidance, and 45-minute flight time per battery pack.',
    highlights: [
      'Sub-249g ultralight folding frame (No FAA registration required in many regions)',
      '4K/60fps 10-bit D-Log M HDR cinematic video with f/1.7 aperture',
      'Omnidirectional binocular vision obstacle avoidance sensing',
      'Up to 20km O4 FHD wireless video transmission',
    ],
    specs: {
      Weight: '249 grams',
      CameraSensor: '1/1.3-inch 48MP CMOS',
      VideoResolution: '4K up to 60fps / 1080p up to 120fps',
      FlightTime: 'Up to 45 Minutes',
      MaxRange: '20 km (FCC Certified)',
      Gimbal: '3-Axis Mechanical Stabilization',
    },
    basePrice: 849.0,
    compareAtPrice: 949.0,
    rating: 4.8,
    reviewCount: 42,
    isFeatured: true,
    isSponsored: true,
    isNewArrival: true,
    isOnSale: false,
    badge: 'New',
    vendorId: 'ven-aerotech',
    vendorName: 'AeroTech Labs',
    vendorRating: 4.9,
    stock: 12,
    primaryImage: '/demo-assets/ecommerce/demo-03/bento-drone.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/bento-drone.jpg',
      '/demo-assets/ecommerce/demo-03/prod-drone.jpg',
    ],
    locationCity: 'San Francisco, CA',
    variants: [
      {
        id: 'var-drone-carbon',
        name: 'Carbon Weave Gray',
        colorHex: '#334155',
        sku: 'AT-DRN-CRB',
        price: 849.0,
        compareAtPrice: 949.0,
        inventory: 8,
        image: '/demo-assets/ecommerce/demo-03/bento-drone.jpg',
      },
      {
        id: 'var-drone-arctic',
        name: 'Glacier White',
        colorHex: '#E2E8F0',
        sku: 'AT-DRN-WHT',
        price: 849.0,
        compareAtPrice: 949.0,
        inventory: 4,
        image: '/demo-assets/ecommerce/demo-03/bento-drone.jpg',
      },
    ],
  },
  {
    id: 'prod-horizon-34-curved-monitor',
    slug: 'horizon-34-curved-monitor',
    title: 'Horizon 34-Inch Curved QD-OLED Ultrawide Studio Monitor',
    brand: 'CyberForge',
    category: 'accessories',
    subCategory: 'Curved Ultrawide',
    description:
      'Immersive panoramic productivity. Featuring a quantum dot OLED panel with 3440x1440 WQHD resolution, 175Hz refresh rate, 0.03ms response time, 99.3% DCI-P3 color calibration with factory Delta-E < 1, and 90W USB-C single-cable power delivery.',
    highlights: [
      '34" Quantum Dot OLED (3440 x 1440 WQHD) at 175Hz',
      'Near-instantaneous 0.03ms GtG pixel response time',
      'True Black 400 HDR with infinite contrast ratio',
      'Integrated KVM switch and 90W USB-C Power Delivery',
    ],
    specs: {
      PanelSize: '34" Diagonal Curved 1800R',
      Resolution: '3440 x 1440 WQHD',
      RefreshRate: '175Hz',
      PanelType: 'QD-OLED',
      ColorAccuracy: '99.3% DCI-P3, Factory Delta E < 1',
      Ports: '1x USB-C (90W PD), 2x HDMI 2.1, 1x DP 1.4',
    },
    basePrice: 999.0,
    compareAtPrice: 1199.0,
    rating: 4.9,
    reviewCount: 53,
    isFeatured: false,
    isSponsored: true,
    isNewArrival: false,
    isOnSale: true,
    badge: 'Sale',
    vendorId: 'ven-cyberforge',
    vendorName: 'CyberForge Hardware',
    vendorRating: 4.8,
    stock: 14,
    primaryImage: '/demo-assets/ecommerce/demo-03/prod-monitor.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/prod-monitor.jpg',
      '/demo-assets/ecommerce/demo-03/hero-banner.jpg',
    ],
    locationCity: 'Austin, TX',
    variants: [
      {
        id: 'var-mon-silver',
        name: 'Anodized Silver Stand',
        colorHex: '#94A3B8',
        sku: 'CF-HRZ34-SLV',
        price: 999.0,
        compareAtPrice: 1199.0,
        inventory: 14,
        image: '/demo-assets/ecommerce/demo-03/prod-monitor.jpg',
      },
    ],
  },
  {
    id: 'prod-cybertype-ergonomic-keyboard',
    slug: 'cybertype-ergonomic-keyboard',
    title: 'CyberType Pro Split Ergonomic Mechanical Keyboard',
    brand: 'CyberForge',
    category: 'accessories',
    subCategory: 'Ergonomic Keyboards',
    description:
      'Pain-free typing for programmers, writers, and power users. Alice split ergonomic layout, CNC machined anodized aluminum body, hot-swappable Kailh Box Linear switches, per-key north-facing RGB with ice blue preset, and Bluetooth 5.2 multi-device pairing.',
    highlights: [
      'Ergonomic Alice split curve promoting natural wrist alignment',
      'CNC milled aerospace aluminum enclosure with acoustic silicone damping',
      'Hot-swappable switch sockets (Compatible with 3-pin & 5-pin switches)',
      'Tri-mode connection: 2.4G wireless, Bluetooth, and detachable Type-C',
    ],
    specs: {
      Layout: 'Alice Split Ergonomic 75% Layout',
      Switches: 'Pre-lubed Kailh Box Deep Linear',
      CaseMaterial: '6063 Aluminum CNC Anodized',
      Battery: '4,000 mAh Rechargeable (Up to 200 Hours)',
      Weight: '1.45 kg',
    },
    basePrice: 219.0,
    compareAtPrice: 249.0,
    rating: 4.8,
    reviewCount: 71,
    isFeatured: false,
    isNewArrival: true,
    isOnSale: false,
    badge: 'New',
    vendorId: 'ven-cyberforge',
    vendorName: 'CyberForge Hardware',
    vendorRating: 4.8,
    stock: 30,
    primaryImage: '/demo-assets/ecommerce/demo-03/prod-keyboard.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-03/prod-keyboard.jpg',
      '/demo-assets/ecommerce/demo-03/hero-banner.jpg',
    ],
    locationCity: 'Austin, TX',
    variants: [
      {
        id: 'var-kb-slate',
        name: 'Matte Slate Gray',
        colorHex: '#1E293B',
        sku: 'CF-CBT-SLT',
        price: 219.0,
        compareAtPrice: 249.0,
        inventory: 18,
        image: '/demo-assets/ecommerce/demo-03/prod-keyboard.jpg',
      },
      {
        id: 'var-kb-silver',
        name: 'Raw Aluminum Silver',
        colorHex: '#E2E8F0',
        sku: 'CF-CBT-SLV',
        price: 219.0,
        compareAtPrice: 249.0,
        inventory: 12,
        image: '/demo-assets/ecommerce/demo-03/prod-keyboard.jpg',
      },
    ],
  },
  {
    id: 'prod-auravision-smart-camera',
    slug: 'auravision-smart-camera',
    title: 'AuraVision 4K AI Smart Home Camera & Magnetic Hub',
    brand: 'AeroTech',
    category: 'smart-home',
    subCategory: 'AI Security Cams',
    description:
      'Discreet residential intelligence. 4K HDR Sony Starvis 2 sensor for full color night vision in near-pitch darkness. On-device neural processing recognizes people, pets, packages, and vehicles with zero cloud latency. Includes versatile magnetic 360 wall mount.',
    highlights: [
      '4K Ultra HD video with Sony Starvis 2 Low-Light sensor',
      'Edge AI local recognition with 100% private on-device storage',
      'Magnetic ball-joint mount for wall, ceiling, or desktop positioning',
      'Dual-band Wi-Fi 6 with HomeKit, Google Home, and Matter compatibility',
    ],
    specs: {
      Resolution: '4K Ultra HD (3840 x 2160) at 30fps',
      FieldOfView: '150° Diagonal Wide Angle',
      NightVision: 'Color Night Vision with dual IR illuminators',
      Storage: 'MicroSD up to 512GB & Local NAS RTSP Streaming',
      Power: 'USB-C 5V/2A or Optional Solar Panel',
    },
    basePrice: 159.0,
    compareAtPrice: 189.0,
    rating: 4.7,
    reviewCount: 61,
    isFeatured: false,
    isSponsored: false,
    isNewArrival: false,
    isOnSale: true,
    badge: 'Sale',
    vendorId: 'ven-aerotech',
    vendorName: 'AeroTech Labs',
    vendorRating: 4.9,
    stock: 50,
    primaryImage: '/demo-assets/ecommerce/demo-03/prod-cam.jpg',
    galleryImages: ['/demo-assets/ecommerce/demo-03/prod-cam.jpg'],
    locationCity: 'San Francisco, CA',
    variants: [
      {
        id: 'var-cam-white',
        name: 'Ceramic Chalk White',
        colorHex: '#F8FAFC',
        sku: 'AT-AV4K-WHT',
        price: 159.0,
        compareAtPrice: 189.0,
        inventory: 50,
        image: '/demo-assets/ecommerce/demo-03/prod-cam.jpg',
      },
    ],
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-nexus10',
    code: 'NEXUS10',
    description: '10% off your entire order for tech community members',
    discountPercent: 10,
    usageCount: 142,
    isActive: true,
    expiryDate: '2027-12-31',
  },
  {
    id: 'coup-freeship',
    code: 'FREESHIP',
    description: 'Free expedited delivery on any order size',
    freeShipping: true,
    usageCount: 89,
    isActive: true,
    expiryDate: '2027-12-31',
  },
  {
    id: 'coup-tech20',
    code: 'TECH20',
    description: '$20 flat discount on orders over $150',
    discountAmount: 20,
    minSpend: 150,
    usageCount: 54,
    isActive: true,
    expiryDate: '2027-12-31',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-840291',
    orderNumber: 'KG-2026-4821',
    trackingNumber: 'KG-TRK-840291',
    date: '2026-09-24T14:32:00Z',
    customerName: 'Marcus Vance',
    customerEmail: 'm.vance@techstudio.io',
    phone: '+1 (415) 890-2134',
    address: '742 Evergreen Terrace, Apt 4B',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94107',
    country: 'United States',
    shippingMethod: 'Express Air (2-3 Business Days)',
    items: [
      {
        productId: 'prod-apexbook-ultra-16',
        variantId: 'var-apex-black',
        title: 'ApexBook Ultra 16 Creator Studio (M5 Pro Chip)',
        variantName: 'Space Black',
        price: 2899.0,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-03/prod-laptop.jpg',
      },
    ],
    subtotal: 2899.0,
    shipping: 0.0,
    tax: 231.92,
    discount: 0.0,
    total: 3130.92,
    status: 'Dispatched',
    estimatedDelivery: 'Sep 28, 2026',
  },
  {
    id: 'ord-840292',
    orderNumber: 'KG-2026-4822',
    trackingNumber: 'KG-TRK-840292',
    date: '2026-09-25T09:15:00Z',
    customerName: 'Elena Rostova',
    customerEmail: 'elena.rostova@designworks.com',
    phone: '+1 (512) 670-4921',
    address: '1204 Congress Ave, Suite 300',
    city: 'Austin',
    state: 'TX',
    postalCode: '78701',
    country: 'United States',
    shippingMethod: 'Standard Courier (4-5 Business Days)',
    items: [
      {
        productId: 'prod-valkyrie-pro-controller',
        variantId: 'var-valk-white',
        title: 'Valkyrie Pro Wireless Hall-Effect Esports Controller',
        variantName: 'Arctic White & Cyan Glow',
        price: 169.0,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
      },
      {
        productId: 'prod-hypervolt-gan-station',
        variantId: 'var-volt-trans',
        title: 'HyperVolt 240W Desktop GaN Fast Charging Station',
        variantName: 'Transparent Cyber Edition',
        price: 129.0,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
      },
    ],
    subtotal: 298.0,
    shipping: 0.0,
    tax: 23.84,
    discount: 29.8,
    total: 292.04,
    couponCode: 'NEXUS10',
    status: 'Processing',
    estimatedDelivery: 'Oct 01, 2026',
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-apexbook-ultra-16',
    author: 'Alex K., Lead Unreal Engineer',
    rating: 5,
    date: 'Sep 21, 2026',
    title: 'Flawless build quality and thermal stability',
    comment:
      'Compiling huge C++ projects and rendering 8K footage in DaVinci Resolve without the fans screaming is astonishing. The keyboard feel is crisp, and the OLED display is color-accurate right out of the box.',
    verified: true,
    status: 'Approved',
  },
  {
    id: 'rev-2',
    productId: 'prod-valkyrie-pro-controller',
    author: 'Devon T., Competitive FPS Player',
    rating: 5,
    date: 'Sep 18, 2026',
    title: 'The Hall effect sticks ruined every other gamepad for me',
    comment:
      'Zero deadzones with razor-sharp response. The tactile mouse click buttons give an unfair advantage in rapid-fire games.',
    verified: true,
    status: 'Approved',
  },
  {
    id: 'rev-3',
    productId: 'prod-hypervolt-gan-station',
    author: 'Sarah M., Hardware Reviewer',
    rating: 5,
    date: 'Sep 15, 2026',
    title: 'Replaced 4 clunky power bricks on my desk',
    comment:
      'The live wattage OLED screen is both genuinely useful and looks incredible. Stays cool even while fast charging my 140W laptop and phone simultaneously.',
    verified: true,
    status: 'Approved',
  },
];

export const initialArticles: Article[] = [
  {
    id: 'art-1',
    slug: 'minimalist-creator-workstation-guide',
    title: 'The 2026 Minimalist Desk Architecture: Engineering Flow State',
    excerpt:
      'How titanium ultrabooks, thunderbolt hubs, and QD-OLED panels form an ergonomic creative sanctuary with zero cord clutter.',
    content: `Crafting a high-performance desk setup is an exercise in intentionality. In 2026, advances in single-cable Thunderbolt 5 protocols and Gallium Nitride power distribution allow creative professionals to drive dual 4K monitors and high-speed RAID storage with an absolute minimum of physical footprint.`,
    coverImage: '/demo-assets/ecommerce/demo-03/hero-banner.jpg',
    author: 'Kinetic Editorial',
    authorRole: 'Hardware Architecture Lead',
    date: 'Sep 22, 2026',
    readTime: '5 min read',
    category: 'Workstations',
  },
  {
    id: 'art-2',
    slug: 'hall-effect-controllers-deep-dive',
    title: 'Why Potentiometers are Dead: The Physics of Hall Effect Sensors',
    excerpt:
      'Inside the contactless electromagnetic analog sticks ending joystick drift forever in esports gaming hardware.',
    content: `Traditional game controllers rely on carbon resistive film tracks that physically rub together thousands of times per session. Contactless Hall effect sensors measure micro-variations in magnetic flux density without any physical contact, guaranteeing permanent calibration.`,
    coverImage: '/demo-assets/ecommerce/demo-03/bento-gaming.jpg',
    author: 'Devon Takahashi',
    authorRole: 'Esports Technology Contributor',
    date: 'Sep 19, 2026',
    readTime: '4 min read',
    category: 'Gaming Hardware',
  },
  {
    id: 'art-3',
    slug: 'gan-power-evolution-explained',
    title: 'Gallium Nitride Demystified: How GaN III Delivers 240W in Your Pocket',
    excerpt:
      'Exploring how high-bandgap semiconductors are replacing silicon to deliver cool, efficient, ultra-dense desktop power.',
    content: `Silicon has reached its theoretical breakdown voltage threshold in ultra-compact packaging. Gallium Nitride features a 3x wider bandgap and 1,000x faster electron velocity, enabling power converters that operate at 10x higher switching frequencies with minimal heat waste.`,
    coverImage: '/demo-assets/ecommerce/demo-03/bento-power.jpg',
    author: 'Dr. Aris Thorne',
    authorRole: 'Semiconductor Physicist',
    date: 'Sep 14, 2026',
    readTime: '6 min read',
    category: 'Power Engineering',
  },
  {
    id: 'art-4',
    slug: 'spatial-audio-and-lossless-codecs',
    title: 'Beyond Stereo: How Head-Tracking Spatial ANC Redefines Music Production',
    excerpt:
      'A deep dive into high-bitrate LDAC wireless protocols and personalized binaural HRTF acoustic mapping.',
    content: `Personalized Head-Related Transfer Function (HRTF) algorithms combined with 96kHz/24-bit lossless wireless streaming allow modern audiophiles to experience the acoustic spaciousness of a million-dollar studio control room inside a lightweight pair of over-ear headphones.`,
    coverImage: '/demo-assets/ecommerce/demo-03/bento-audio.jpg',
    author: 'Miriam Chen',
    authorRole: 'Acoustics Specialist',
    date: 'Sep 10, 2026',
    readTime: '5 min read',
    category: 'Acoustics',
  },
];
