import {
  Product,
  ProductCategory,
  Order,
  Combo,
  Coupon,
  Review,
  Banner,
  PopupSettings,
  Integration,
  StaffMember,
  RolePermission,
  ActivityLogItem,
  StoreSettings,
  MediaAsset,
} from '../_types';

export const initialSettings: StoreSettings = {
  storeName: 'Shuddha Harvest',
  storeTagline: '১০০% খাঁটি ও প্রাকৃতিক উপাদানে তৈরি খাদ্যপণ্য | Farm-Fresh Organic Pantry',
  currency: '৳',
  announcementEnabled: true,
  announcementText: '🔥 রমজান স্পেশাল অফার: সারা দেশে ফ্রি ডেলিভারি পেতে ন্যূনতম অর্ডার করুন ৳২,০০০+ | কুপন কোড: SHUDDHA10',
  phone: '+880 1711-234567',
  email: 'support@shuddhademo.com',
  address: 'Plot 42, Road 11, Banani, Dhaka-1213, Bangladesh',
  freeShippingThreshold: 2000,
  insideDhakaShippingFee: 60,
  outsideDhakaShippingFee: 120,
  sessionTimeoutMinutes: 60,
};

export const initialCategories: ProductCategory[] = [
  {
    id: 'c1',
    slug: 'honey',
    name: 'Honey',
    bengaliName: 'মধু',
    iconName: 'Droplet',
    image: '/demo-assets/ecommerce/sundarban-honey.jpg',
    productCount: 4,
    order: 1,
    isActive: true,
    description: '১০০% খাঁটি সুন্দরবন ও পাহাড়ি মধু সংগ্রহ',
  },
  {
    id: 'c2',
    slug: 'oil-and-ghee',
    name: 'Oil & Ghee',
    bengaliName: 'তেল ও ঘি',
    iconName: 'Flame',
    image: '/demo-assets/ecommerce/gawa-ghee.jpg',
    productCount: 6,
    order: 2,
    isActive: true,
    description: 'ঐতিহ্যবাহী ঘানিভাঙ্গা সরিষার তেল ও খাঁটি গাওয়া ঘি',
  },
  {
    id: 'c3',
    slug: 'dates',
    name: 'Dates',
    bengaliName: 'খেজুর',
    iconName: 'Sun',
    image: '/demo-assets/ecommerce/ajwa-dates.jpg',
    productCount: 5,
    order: 3,
    isActive: true,
    description: 'মদিনা ও মধ্যপ্রাচ্য থেকে সরাসরি আমদানিকৃত প্রিমিয়াম খেজুর',
  },
  {
    id: 'c4',
    slug: 'spices',
    name: 'Spices',
    bengaliName: 'মশলা',
    iconName: 'Sparkles',
    image: '/demo-assets/ecommerce/turmeric-spices.jpg',
    productCount: 5,
    order: 4,
    isActive: true,
    description: 'ভেজালমুক্ত খাঁটি গুড়া ও আস্ত পাহাড়ি মশলা',
  },
  {
    id: 'c5',
    slug: 'nuts-and-seeds',
    name: 'Nuts & Seeds',
    bengaliName: 'বাদাম ও বীজ',
    iconName: 'Leaf',
    image: '/demo-assets/ecommerce/nuts-seeds.jpg',
    productCount: 4,
    order: 5,
    isActive: true,
    description: 'পুষ্টিকর কাঁচা কাঠবাদাম, কাজুবাদাম ও অরগানিক চিয়া বীজ',
  },
  {
    id: 'c6',
    slug: 'beverage',
    name: 'Beverage',
    bengaliName: 'চা ও পানীয়',
    iconName: 'Coffee',
    image: '/demo-assets/ecommerce/hero-banner.jpg',
    productCount: 3,
    order: 6,
    isActive: true,
    description: 'সিলেটের প্রিমিয়াম চা ও আয়ুর্বেদিক পানীয়',
  },
  {
    id: 'c7',
    slug: 'flours-and-lentils',
    name: 'Flours & Lentils',
    bengaliName: 'চাল ও ডাল',
    iconName: 'Wheat',
    image: '/demo-assets/ecommerce/mid-banner.jpg',
    productCount: 3,
    order: 7,
    isActive: true,
    description: 'সুগন্ধি চিনিগুঁড়া চাল ও দেশি মসুর ডাল',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'p1',
    slug: 'gawa-ghee-1kg',
    name: 'Gawa Ghee 1kg',
    bengaliName: 'খাঁটি গাওয়া ঘি ১ কেজি (দানাযুক্ত)',
    sku: 'SH-GH-01',
    category: 'oil-and-ghee',
    categoryName: 'Oil & Ghee',
    price: 1990,
    compareAtPrice: 2250,
    stock: 18,
    status: 'active',
    badge: 'Best Seller',
    isFeatured: true,
    isTopSelling: true,
    rating: 4.9,
    reviewCount: 142,
    shortDescription: 'দেশি গরুর দুধের ননি থেকে ঐতিহ্যবাহী ঘোল মন্থন পদ্ধতিতে প্রস্তুত খাঁটি সুগন্ধি দানাযুক্ত গাওয়া ঘি।',
    description:
      'শুদ্ধ হারভেস্টের গাওয়া ঘি শতভাগ প্রাকৃতিক ও পুষ্টিকর। এটি সরাসরি খামার থেকে সংগৃহীত খাঁটি দেশি গরুর কাঁচা দুধ থেকে তৈরি। সনাতন বিলোনা পদ্ধতিতে মাখন মন্থন করে হালকা আঁচে জ্বাল দিয়ে তৈরি হয় এই ঘি, যা বজায় রাখে এর প্রাকৃতিক সোনালী বর্ণ, সুগন্ধ ও আকর্ষণীয় দানাদার টেক্সচার। কোনো প্রকার কৃত্রিম ফ্লেভার, প্রিজারভেটিভ বা পাম অয়েল নেই।',
    specifications: [
      { label: 'Brand', value: 'Shuddha Harvest' },
      { label: 'Net Weight', value: '1000g (1 kg)' },
      { label: 'Source', value: '100% Pure Grass-Fed Cow Milk' },
      { label: 'Process', value: 'Traditional Bilona Churning (বিলোনা পদ্ধতি)' },
      { label: 'Texture', value: 'Naturally Granular (দানাযুক্ত)' },
      { label: 'Shelf Life', value: '12 Months' },
      { label: 'Storage', value: 'Store in cool dry place, away from sunlight' },
    ],
    images: [
      '/demo-assets/ecommerce/gawa-ghee.jpg',
      '/demo-assets/ecommerce/ghee-bowl.jpg',
      '/demo-assets/ecommerce/mid-banner.jpg',
      '/demo-assets/ecommerce/hero-banner.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '1 kg',
    seoTitle: 'Pure Gawa Ghee 1kg | Shuddha Harvest Organic',
    seoDescription: 'Buy 100% Pure Deshi Cow Gawa Ghee 1kg online at best price in Bangladesh. Traditional granular texture & authentic aroma.',
  },
  {
    id: 'p2',
    slug: 'deshi-mustard-oil-2l',
    name: 'Deshi Mustard Oil 2 Liter',
    bengaliName: 'ঘানিভাঙ্গা খাঁটি সরিষার তেল ২ লিটার',
    sku: 'SH-MO-02',
    category: 'oil-and-ghee',
    categoryName: 'Oil & Ghee',
    price: 680,
    compareAtPrice: 750,
    stock: 35,
    status: 'active',
    badge: '100% Pure',
    isFeatured: true,
    isTopSelling: true,
    rating: 4.8,
    reviewCount: 98,
    shortDescription: 'কাঠের ঘানিতে ভাঙা প্রথম চাপের খাঁটি দেশি মাঘী সরিষার ঝাঁঝালো তেল।',
    description:
      'শুদ্ধ হারভেস্টের সরিষার তেল বাছাইকৃত দেশি সরিষা থেকে কাঠের ঘানিতে মৃদু চাপে নিষ্কাশিত হয়। কোনো ক্ষতিকর কেমিক্যাল বা হিট ট্রিটমেন্ট ছাড়াই প্রাকৃতিক ফিল্টারিং প্রক্রিয়ায় প্রস্তুত হওয়ায় সরিষার আসল ঝাঁঝ ও খাদ্যমান সম্পূর্ণ বজায় থাকে। প্রতিদিনের রান্না ও ভর্তায় আনে অতুলনীয় স্বাদ।',
    specifications: [
      { label: 'Brand', value: 'Shuddha Harvest' },
      { label: 'Volume', value: '2 Liters' },
      { label: 'Extraction', value: 'Cold Pressed Wood Churn (কাঠের ঘানি)' },
      { label: 'Seed Variety', value: 'Deshi Yellow & Black Mustard' },
      { label: 'Purity', value: '100% Natural, Unrefined' },
      { label: 'Shelf Life', value: '18 Months' },
    ],
    images: [
      '/demo-assets/ecommerce/mustard-oil.jpg',
      '/demo-assets/ecommerce/mid-banner.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '2 Liters',
    seoTitle: 'Deshi Mustard Oil 2 Liter | Cold Pressed Mustard Oil',
    seoDescription: 'Cold pressed unrefined wooden churned deshi mustard oil 2 liter. Natural pungency and farm purity.',
  },
  {
    id: 'p3',
    slug: 'sundarban-wild-honey-1kg',
    name: 'Sundarban Wild Honey 1kg',
    bengaliName: 'সুন্দরবনের প্রাকৃতিক খলিশা ফুলের মধু ১ কেজি',
    sku: 'SH-HN-01',
    category: 'honey',
    categoryName: 'Honey',
    price: 1250,
    compareAtPrice: 1400,
    stock: 22,
    status: 'active',
    badge: 'Raw & Pure',
    isFeatured: true,
    isTopSelling: true,
    rating: 5.0,
    reviewCount: 86,
    shortDescription: 'সুন্দরবনের গভীর অরণ্যের মৌয়ালদের সংগৃহীত প্রাকৃতিক কাঁচা মধু।',
    description:
      'সুন্দরবনের গভীর বনের খলিশা ও গরান ফুলের খাঁটি নেকটার থেকে মৌমাছিদের তৈরি এই মধু। এতে কোনো গরম প্রক্রিয়াকরণ বা কৃত্রিম চিনির মিশ্রণ নেই। প্রাকৃতিক অ্যান্টিঅক্সিডেন্ট ও অ্যান্টিব্যাকটেরিয়াল উপাদানে সমৃদ্ধ এই মধু দেহের রোগ প্রতিরোধ ক্ষমতা বাড়াতে অত্যন্ত কার্যকর।',
    specifications: [
      { label: 'Brand', value: 'Shuddha Harvest' },
      { label: 'Net Weight', value: '1000g' },
      { label: 'Floral Source', value: 'Sundarban Khalisha & Goran Flower' },
      { label: 'Grade', value: 'Raw Unpasteurized Honey' },
      { label: 'Certification', value: '100% Lab Tested Pure' },
    ],
    images: [
      '/demo-assets/ecommerce/sundarban-honey.jpg',
      '/demo-assets/ecommerce/black-seed-honey.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '1 kg',
    seoTitle: 'Raw Sundarban Wild Honey 1kg | Shuddha Harvest',
    seoDescription: 'Authentic Sundarban wild honey 1kg directly collected by Mouyals. 100% raw and chemical free.',
  },
  {
    id: 'p4',
    slug: 'black-seed-honey-1kg',
    name: 'Black Seed Honey 1kg',
    bengaliName: 'কালোজিরা ফুলের খাঁটি মধু ১ কেজি',
    sku: 'SH-HN-02',
    category: 'honey',
    categoryName: 'Honey',
    price: 1450,
    compareAtPrice: 1600,
    stock: 15,
    status: 'active',
    badge: 'Medicinal',
    isFeatured: true,
    isTopSelling: true,
    rating: 4.9,
    reviewCount: 64,
    shortDescription: 'কালোজিরা ফুল থেকে সংগৃহীত বিশেষ পুষ্টিগুণসমৃদ্ধ গাড় বাদামী মধু।',
    description:
      'কালোজিরা ফুলের মাঠে মৌমাছি দ্বারা সংগৃহীত খাঁটি মধু। এতে কালোজিরার রোগ নিরাময়ী প্রাকৃতিক উপাদান বিদ্যমান থাকায় এটি শারীরিক দুর্বলতা ও ঠান্ডাজনিত সমস্যায় বিশেষ উপকারী।',
    specifications: [
      { label: 'Brand', value: 'Shuddha Harvest' },
      { label: 'Net Weight', value: '1000g' },
      { label: 'Floral Source', value: 'Nigella Sativa (Kalonji Flower)' },
      { label: 'Color', value: 'Dark Rich Amber' },
    ],
    images: [
      '/demo-assets/ecommerce/black-seed-honey.jpg',
      '/demo-assets/ecommerce/sundarban-honey.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '1 kg',
  },
  {
    id: 'p5',
    slug: 'saudi-ajwa-dates-500g',
    name: 'Saudi Ajwa Dates 500g',
    bengaliName: 'মদিনার প্রিমিয়াম আজওয়া খেজুর ৫০০ গ্রাম',
    sku: 'SH-DT-01',
    category: 'dates',
    categoryName: 'Dates',
    price: 950,
    compareAtPrice: 1100,
    stock: 40,
    status: 'active',
    badge: 'VIP Box',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 53,
    shortDescription: 'মদিনা মুনাওয়ারা থেকে সরাসরি সংগৃহীত নরম, রসালো ও বরকতপূর্ণ কালো আজওয়া খেজুর।',
    description:
      'মদিনার নির্বাচিত বাগান থেকে সংগৃহীত প্রিমিয়াম গ্রেড আজওয়া খেজুর। নরম টেক্সচার, প্রাকৃতিক মিষ্টি এবং অসাধারণ পুষ্টিগুণ সম্পন্ন। উপহার বা পরিবারের প্রতিদিনের সুস্থতায় আদর্শ।',
    specifications: [
      { label: 'Origin', value: 'Medina Munawwarah, Saudi Arabia' },
      { label: 'Net Weight', value: '500g Luxury Box' },
      { label: 'Grade', value: 'Jumbo Premium A+' },
    ],
    images: [
      '/demo-assets/ecommerce/ajwa-dates.jpg',
      '/demo-assets/ecommerce/mid-banner.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '500g',
  },
  {
    id: 'p6',
    slug: 'medjool-dates-royal-1kg',
    name: 'Medjool Royal Dates 1kg',
    bengaliName: 'জর্ডান রয়েল মেদজুল খেজুর ১ কেজি',
    sku: 'SH-DT-02',
    category: 'dates',
    categoryName: 'Dates',
    price: 1750,
    compareAtPrice: 1950,
    stock: 28,
    status: 'active',
    badge: 'Super Jumbo',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 39,
    shortDescription: 'খেজুরের রাজা মেদজুল—আকারে বড়, অত্যন্ত নরম এবং ক্যারামেল স্বাদের।',
    description:
      'স্বাদে গন্ধে অতুলনীয় মেদজুল খেজুর। এর পাতলা চামড়া ও পুরু রসালো মাংসের কারণে এটি আন্তর্জাতিকভাবে অন্যতম জনপ্রিয় প্রিমিয়াম ফল।',
    specifications: [
      { label: 'Origin', value: 'Jordan Valley' },
      { label: 'Net Weight', value: '1000g' },
      { label: 'Size', value: 'Super Jumbo' },
    ],
    images: [
      '/demo-assets/ecommerce/ajwa-dates.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '1 kg',
  },
  {
    id: 'p7',
    slug: 'organic-ground-turmeric-200g',
    name: 'Organic Ground Turmeric 200g',
    bengaliName: 'পাহাড়ি খাঁটি হলুদের গুঁড়া ২০০ গ্রাম',
    sku: 'SH-SP-01',
    category: 'spices',
    categoryName: 'Spices',
    price: 180,
    compareAtPrice: 220,
    stock: 50,
    status: 'active',
    badge: 'Pure Curcumin',
    isFeatured: true,
    rating: 4.7,
    reviewCount: 31,
    shortDescription: 'পাহাড়ের খাঁটি হলুদ শুকিয়ে স্বাস্থ্যসম্মত পরিবেশে চূর্ণ করা হলুদের গুড়া।',
    description:
      'খাগড়াছড়ির পাহাড়ি অঞ্চল থেকে সংগৃহীত প্রাকৃতিক হলুদ দিয়ে প্রস্তুত। এতে প্রাকৃতিকভাবে উচ্চমাত্রার কারকিউমিন উপাদান রয়েছে যা রান্নায় দেয় নিখুঁত সোনালী আভা এবং বজায় রাখে রোগ প্রতিরোধ ক্ষমতা।',
    specifications: [
      { label: 'Brand', value: 'Shuddha Harvest' },
      { label: 'Net Weight', value: '200g Jar' },
      { label: 'Curcumin Content', value: '> 3.5%' },
      { label: 'Additives', value: 'Zero Artificial Color or Starch' },
    ],
    images: [
      '/demo-assets/ecommerce/turmeric-spices.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '200g',
  },
  {
    id: 'p8',
    slug: 'raw-organic-mixed-nuts-500g',
    name: 'Raw Organic Mixed Nuts 500g',
    bengaliName: 'প্রিমিয়াম কাঠবাদাম, কাজু ও চিয়া বীজ ৫০০ গ্রাম',
    sku: 'SH-NT-01',
    category: 'nuts-and-seeds',
    categoryName: 'Nuts & Seeds',
    price: 850,
    compareAtPrice: 980,
    stock: 32,
    status: 'active',
    badge: 'Superfood',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 47,
    shortDescription: 'ক্যালিফোর্নিয়া কাঠবাদাম, কাজুবাদাম এবং মেক্সিকান ব্ল্যাক চিয়া বীজের প্রিমিয়াম পুষ্টিকর ব্লেন্ড।',
    description:
      'প্রতিদিনের প্রোটিন ও ওমেগা-৩ ফ্যাটি এসিডের চাহিদা মেটাতে সেরা তিনটি সুপারফুডের কম্বিনেশন। সকালের নাস্তায় বা বিকেলের স্ন্যাকসে অত্যন্ত স্বাস্থ্যকর।',
    specifications: [
      { label: 'Mix Ratio', value: 'Almonds 40%, Cashews 40%, Chia Seeds 20%' },
      { label: 'Net Weight', value: '500g Glass Jar' },
      { label: 'Processing', value: 'Raw, Non-Roasted, Unsalted' },
    ],
    images: [
      '/demo-assets/ecommerce/nuts-seeds.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '500g',
  },
  {
    id: 'p9',
    slug: 'gawa-ghee-combo-offer',
    name: 'Gawa Ghee 1kg + Chicken Masala Combo',
    bengaliName: 'গাওয়া ঘি ১ কেজি + চিকেন মশলা স্পেশাল কম্বো',
    sku: 'SH-CB-01',
    category: 'oil-and-ghee',
    categoryName: 'Oil & Ghee',
    price: 1990,
    compareAtPrice: 2350,
    stock: 14,
    status: 'active',
    badge: 'Combo Offer',
    isFeatured: true,
    isTopSelling: true,
    rating: 5.0,
    reviewCount: 78,
    shortDescription: '১ কেজি খাঁটি গাওয়া ঘির সাথে আকর্ষণীয় অফারে স্পেশাল রয়েল চিকেন কারি মশলা বক্স একদম ফ্রি!',
    description:
      'আমাদের সেরা বিক্রিত গাওয়া ঘি ১ কেজি প্যাকেজের সাথে পাচ্ছেন প্রিমিয়াম চিকেন রোস্ট ও কারি মশলার এক্সক্লুসিভ গিফট প্যাক। ঘরোয়া দাওয়াত বা স্পেশাল রান্নার জন্য এটি অতুলনীয় কম্বিনেশন।',
    specifications: [
      { label: 'Package Includes', value: '1kg Gawa Ghee Tin + 100g Chicken Masala Box' },
      { label: 'Packaging', value: 'Festive Ribbon Tied Luxury Box' },
      { label: 'Total Value', value: '৳2,350' },
      { label: 'Special Price', value: '৳1,990' },
    ],
    images: [
      '/demo-assets/ecommerce/gawa-ghee.jpg',
      '/demo-assets/ecommerce/ghee-bowl.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '1.1 kg Combo',
  },
  {
    id: 'p10',
    slug: 'cold-pressed-coconut-oil-500ml',
    name: 'Cold Pressed Virgin Coconut Oil 500ml',
    bengaliName: 'কোল্ড প্রেসড এক্সট্রা ভার্জিন নারিকেল তেল ৫০০ মি.লি.',
    sku: 'SH-MO-03',
    category: 'oil-and-ghee',
    categoryName: 'Oil & Ghee',
    price: 480,
    compareAtPrice: 550,
    stock: 20,
    status: 'active',
    rating: 4.8,
    reviewCount: 26,
    shortDescription: 'তাজা নারিকেলের দুধ থেকে সেন্ট্রিফিউগাল প্রযুক্তিতে তৈরি খাঁটি খাওয়ার উপযোগী ভার্জিন কোকোনাট অয়েল।',
    description:
      'খাবারে বা ত্বকের যত্নে ব্যবহারের জন্য ১০০% নিরাপদ ও সুগন্ধযুক্ত কাঁচা নারিকেল তেল। কোনো গরম বা রিফাইনিং ছাড়া তৈরি।',
    specifications: [
      { label: 'Volume', value: '500ml' },
      { label: 'Extraction', value: 'Cold Centrifuged Virgin' },
    ],
    images: [
      '/demo-assets/ecommerce/mustard-oil.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '500 ml',
  },
  {
    id: 'p11',
    slug: 'organic-black-chia-seeds-250g',
    name: 'Organic Black Chia Seeds 250g',
    bengaliName: 'অর্গানিক ব্ল্যাক চিয়া বীজ ২৫০ গ্রাম',
    sku: 'SH-NT-02',
    category: 'nuts-and-seeds',
    categoryName: 'Nuts & Seeds',
    price: 320,
    compareAtPrice: 380,
    stock: 60,
    status: 'active',
    rating: 4.9,
    reviewCount: 89,
    shortDescription: 'ওমেগা-৩ ও ডায়েটারি ফাইবার সমৃদ্ধ আন্তর্জাতিক মানের অর্গানিক চিয়া বীজ।',
    description:
      'ওজন নিয়ন্ত্রণ এবং হৃদযন্ত্র ভালো রাখতে প্রতিদিন পানিতে ভিজিয়ে খাওয়ার জন্য বিশ্বমানের পুষ্টিকর কালো চিয়া বীজ।',
    specifications: [
      { label: 'Net Weight', value: '250g' },
      { label: 'Origin', value: 'South America' },
    ],
    images: [
      '/demo-assets/ecommerce/nuts-seeds.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '250g',
  },
  {
    id: 'p12',
    slug: 'special-biryani-masala-100g',
    name: 'Special Shahi Biryani Masala 100g',
    bengaliName: 'স্পেশাল শাহী বিরিয়ানি মশলা ১০০ গ্রাম',
    sku: 'SH-SP-02',
    category: 'spices',
    categoryName: 'Spices',
    price: 220,
    compareAtPrice: 260,
    stock: 45,
    status: 'active',
    rating: 4.8,
    reviewCount: 42,
    shortDescription: 'জয়ফল, জয়ত্রী, এলাচ ও দারুচিনির নিখুঁত ভারসাম্যে তৈরি খাস বিরিয়ানি মশলা।',
    description:
      'পুরান ঢাকার আসল বিরিয়ানির স্বাদ ও গন্ধ ঘরেই ফিরিয়ে আনতে খাঁটি আস্ত মশলা কাঠখোলায় টেলে তৈরি এই শাহী মশলা।',
    specifications: [
      { label: 'Net Weight', value: '100g Jar' },
      { label: 'Ingredients', value: '14 Royal Spices Blend' },
    ],
    images: [
      '/demo-assets/ecommerce/turmeric-spices.jpg',
    ],
    brand: 'Shuddha Harvest',
    weight: '100g',
  },
];

export const initialCombos: Combo[] = [
  {
    id: 'cb1',
    name: 'Pantry Royal Trio (Ghee + Mustard Oil + Honey)',
    description: 'গাওয়া ঘি ১ কেজি, সরিষার তেল ২ লিটার এবং সুন্দরবন মধু ৫০০ গ্রামের অল-ইন-ওয়ান ফ্যামিলি প্যাক।',
    productIds: ['p1', 'p2', 'p3'],
    originalPrice: 3920,
    discount: 420,
    finalPrice: 3500,
    isActive: true,
    image: '/demo-assets/ecommerce/mid-banner.jpg',
  },
  {
    id: 'cb2',
    name: 'Healthy Breakfast Boost (Chia Seeds + Honey + Mixed Nuts)',
    description: 'সকালের পুষ্টিকর নাস্তার জন্য ব্ল্যাক চিয়া সীড, সুন্দরবন কাঁচা মধু ও মিক্সড নাটস কম্বিনেশন।',
    productIds: ['p3', 'p8', 'p11'],
    originalPrice: 2420,
    discount: 320,
    finalPrice: 2100,
    isActive: true,
    image: '/demo-assets/ecommerce/nuts-seeds.jpg',
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'cp1',
    code: 'SHUDDHA10',
    discountType: 'percentage',
    discountValue: 10,
    minOrder: 1500,
    usedCount: 148,
    usageLimit: 500,
    isActive: true,
    expiresAt: '2026-12-31',
  },
  {
    id: 'cp2',
    code: 'EIDGIFT200',
    discountType: 'fixed',
    discountValue: 200,
    minOrder: 2500,
    usedCount: 89,
    usageLimit: 200,
    isActive: true,
    expiresAt: '2026-11-30',
  },
  {
    id: 'cp3',
    code: 'FREE60',
    discountType: 'fixed',
    discountValue: 60,
    minOrder: 1200,
    usedCount: 215,
    usageLimit: 1000,
    isActive: true,
    expiresAt: '2026-12-31',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'SH-84921',
    date: '2026-09-25 18:42',
    customerName: 'Tanzirul Islam',
    phone: '+880 1819-348210',
    email: 'tanzirul@example.com',
    address: 'House 14, Road 7, Sector 4, Uttara',
    city: 'Inside Dhaka',
    items: [
      {
        productId: 'p1',
        slug: 'gawa-ghee-1kg',
        name: 'Gawa Ghee 1kg',
        price: 1990,
        quantity: 1,
        image: '/demo-assets/ecommerce/gawa-ghee.jpg',
        weight: '1 kg',
      },
      {
        productId: 'p2',
        slug: 'deshi-mustard-oil-2l',
        name: 'Deshi Mustard Oil 2 Liter',
        price: 680,
        quantity: 1,
        image: '/demo-assets/ecommerce/mustard-oil.jpg',
        weight: '2 Liters',
      },
    ],
    subtotal: 2670,
    discount: 200,
    shippingFee: 60,
    total: 2530,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    status: 'Pending',
    notes: 'Please deliver after 4 PM.',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-25 18:42', note: 'Customer placed order via website.' },
    ],
    fraudRisk: 'Low',
  },
  {
    id: 'SH-84920',
    date: '2026-09-25 15:18',
    customerName: 'Farhana Sultana',
    phone: '+880 1712-894021',
    email: 'farhana.s@example.com',
    address: 'Flat 4B, Green Heritage, Dhanmondi 27',
    city: 'Inside Dhaka',
    items: [
      {
        productId: 'p3',
        slug: 'sundarban-wild-honey-1kg',
        name: 'Sundarban Wild Honey 1kg',
        price: 1250,
        quantity: 2,
        image: '/demo-assets/ecommerce/sundarban-honey.jpg',
        weight: '1 kg',
      },
    ],
    subtotal: 2500,
    discount: 250,
    shippingFee: 0,
    total: 2250,
    paymentMethod: 'bKash',
    paymentStatus: 'Paid',
    status: 'Confirmed',
    notes: 'Payment verified via bKash (TrxID: 9J4K2L1M).',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-25 15:18', note: 'Order placed with bKash payment.' },
      { status: 'Confirmed', timestamp: '2026-09-25 15:22', note: 'Payment verified and order confirmed by sales desk.' },
    ],
    fraudRisk: 'Low',
  },
  {
    id: 'SH-84919',
    date: '2026-09-24 20:10',
    customerName: 'Kazi Mahbub Alam',
    phone: '+880 1914-556677',
    email: 'kazi.mahbub@example.com',
    address: 'Nasirabad Housing Society, Road 3, Chittagong',
    city: 'Outside Dhaka',
    items: [
      {
        productId: 'p5',
        slug: 'saudi-ajwa-dates-500g',
        name: 'Saudi Ajwa Dates 500g',
        price: 950,
        quantity: 2,
        image: '/demo-assets/ecommerce/ajwa-dates.jpg',
        weight: '500g',
      },
      {
        productId: 'p8',
        slug: 'raw-organic-mixed-nuts-500g',
        name: 'Raw Organic Mixed Nuts 500g',
        price: 850,
        quantity: 1,
        image: '/demo-assets/ecommerce/nuts-seeds.jpg',
        weight: '500g',
      },
    ],
    subtotal: 2750,
    discount: 275,
    shippingFee: 120,
    total: 2595,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    status: 'Shipped',
    notes: 'Steadfast Courier Tracking: ST-902418',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-24 20:10', note: 'Order placed.' },
      { status: 'Confirmed', timestamp: '2026-09-24 20:45', note: 'Customer phone confirmed.' },
      { status: 'Packed', timestamp: '2026-09-25 09:30', note: 'Package dispatched to dispatch bay.' },
      { status: 'Shipped', timestamp: '2026-09-25 11:15', note: 'Handed over to Steadfast courier.' },
    ],
    fraudRisk: 'Low',
  },
  {
    id: 'SH-84918',
    date: '2026-09-23 11:05',
    customerName: 'Rashidul Hasan',
    phone: '+880 1618-223344',
    email: 'rashid.hasan@example.com',
    address: 'Block C, Bashundhara R/A, Dhaka',
    city: 'Inside Dhaka',
    items: [
      {
        productId: 'p1',
        slug: 'gawa-ghee-1kg',
        name: 'Gawa Ghee 1kg',
        price: 1990,
        quantity: 1,
        image: '/demo-assets/ecommerce/gawa-ghee.jpg',
        weight: '1 kg',
      },
    ],
    subtotal: 1990,
    discount: 0,
    shippingFee: 60,
    total: 2050,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Paid',
    status: 'Delivered',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-23 11:05', note: 'Order received.' },
      { status: 'Confirmed', timestamp: '2026-09-23 11:30', note: 'Order confirmed.' },
      { status: 'Packed', timestamp: '2026-09-23 14:00', note: 'Packed with bubble wrap.' },
      { status: 'Shipped', timestamp: '2026-09-23 16:30', note: 'Sent via Pathao rider.' },
      { status: 'Delivered', timestamp: '2026-09-24 13:20', note: 'Delivered and cash collected ৳2,050.' },
    ],
    fraudRisk: 'Low',
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev1',
    productId: 'p1',
    productName: 'Gawa Ghee 1kg',
    customerName: 'Mahmudul Hasan',
    rating: 5,
    comment:
      'আলহামদুলিল্লাহ ঘিয়ের কোয়ালিটি অসাধারণ! সত্যিকারের দেশি গরুর দুধের ঘ্রাণ ও সুন্দর দানাদার টেক্সচার। ঢাকার ভেতরে মাত্র ২৪ ঘণ্টায় ডেলিভারি পেয়েছি।',
    date: '2026-09-20',
    isVerified: true,
    isVisible: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'rev2',
    productId: 'p1',
    productName: 'Gawa Ghee 1kg',
    customerName: 'Nasrin Akhter',
    rating: 5,
    comment:
      'খাবারে এই ঘি দিলে পুরো বাড়ি সুবাসে ভরে যায়। বাচ্চাদের খিচুড়ির জন্য রেগুলার নিচ্ছি। প্যাকেজিংও খুব প্রটেক্টিভ ছিল।',
    date: '2026-09-18',
    isVerified: true,
    isVisible: true,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'rev3',
    productId: 'p3',
    productName: 'Sundarban Wild Honey 1kg',
    customerName: 'Dr. Shahadat Hossain',
    rating: 5,
    comment:
      'সুন্দরবনের আসল খলিশা মধুর এই প্রাকৃতিক স্বাদ বহু বছর পর পেলাম। কোনরকম কৃত্রিম মিষ্টির গন্ধ নেই। ল্যাব টেস্টে খাঁটি প্রমাণিত।',
    date: '2026-09-15',
    isVerified: true,
    isVisible: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'rev4',
    productId: 'p2',
    productName: 'Deshi Mustard Oil 2 Liter',
    customerName: 'Zubair Ahmed',
    rating: 5,
    comment:
      'ঘানিভাঙ্গা সরিষার তেলের চমৎকার ঝাঁঝ। আলুভর্তা আর ইলিশ ভাজায় এই তেলের বিকল্প নেই। নিয়মিত কাস্টমার হয়ে গেলাম।',
    date: '2026-09-12',
    isVerified: true,
    isVisible: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'b1',
    title: 'Nourishing Better Lives With Pure Organic Harvest',
    bengaliTitle: '১০০% খাঁটি ও অর্গানিক খাদ্যপণ্য সরাসরি খামার থেকে',
    description: 'খাঁটি গাওয়া ঘি, সুন্দরবনের প্রাকৃতিক মধু ও ঘানিভাঙ্গা সরিষার তেলে সমৃদ্ধ ঐতিহ্যবাহী সুস্থ জীবনের নিশ্চয়তা।',
    ctaText: 'অর্ডার করুন এখনই',
    ctaUrl: '/webapp-demo/ecommerce/demo-01/products',
    image: '/demo-assets/ecommerce/hero-banner.jpg',
    order: 1,
    isActive: true,
    type: 'hero_main',
  },
  {
    id: 'b2',
    title: 'Pure Deshi Cow Gawa Ghee & Forest Honey',
    bengaliTitle: 'ঘি ও মধুর বিশেষ অফার প্যাক',
    description: 'ঐতিহ্যবাহী বিলোনা পদ্ধতিতে প্রস্তুত সুগন্ধি গাওয়া ঘি এবং প্রাকৃতিক মধু।',
    ctaText: 'কম্বো দেখুন',
    ctaUrl: '/webapp-demo/ecommerce/demo-01/products/gawa-ghee-1kg',
    image: '/demo-assets/ecommerce/mid-banner.jpg',
    order: 2,
    isActive: true,
    type: 'hero_secondary',
  },
  {
    id: 'b3',
    title: 'The Art of Natural Pantry — Pure, Organic, Sustainable',
    bengaliTitle: 'প্রাকৃতিক ও ভেজালমুক্ত রসুইঘরের বিশ্বস্ত সঙ্গী',
    description: 'প্রিমিয়াম খেজুর, কোল্ড-প্রেসড তেল, খাঁটি মশলা ও অর্গানিক সুপারফুডের পরিপূর্ণ সমাহার।',
    ctaText: 'কালেকশন এক্সপ্লোর করুন',
    ctaUrl: '/webapp-demo/ecommerce/demo-01/products',
    image: '/demo-assets/ecommerce/mid-banner.jpg',
    order: 3,
    isActive: true,
    type: 'mid_promo',
  },
];

export const initialPopup: PopupSettings = {
  isEnabled: true,
  badge: '🎉 বিশেষ ওয়েলকাম ডিসকাউন্ট',
  headline: 'প্রথম অর্ডারে পান অতিরিক্ত ১০% ছাড়!',
  description: 'খাঁটি গাওয়া ঘি, সুন্দরবনের মধু কিংবা ঘানিভাঙ্গা সরিষার তেলে উপভোগ করুন বিশেষ ছাড়।',
  couponCode: 'SHUDDHA10',
  ctaText: 'কুপন প্রয়োগ করুন ও শপ করুন',
  ctaUrl: '/webapp-demo/ecommerce/demo-01/products',
  dismissText: 'ধন্যবাদ, পরে কিনব',
  disclaimer: 'ন্যূনতম ৳১,৫০০ টাকার অর্ডারে এই কুপন প্রযোজ্য। সীমিত সময়ের জন্য।',
  image: '/demo-assets/ecommerce/gawa-ghee.jpg',
};

export const initialIntegrations: Integration[] = [
  {
    id: 'int1',
    name: 'Meta Pixel (Facebook Ads)',
    type: 'meta_pixel',
    placement: 'head',
    code: 'fbq("init", "104928172938102"); fbq("track", "PageView");',
    isEnabled: true,
  },
  {
    id: 'int2',
    name: 'Google Tag Manager',
    type: 'gtm',
    placement: 'head',
    code: "(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});})(window,document,'script','dataLayer','GTM-SHUDDHA1');",
    isEnabled: true,
  },
  {
    id: 'int3 =',
    name: 'TikTok Pixel',
    type: 'tiktok_pixel',
    placement: 'head',
    code: 'ttq.load("C8K3L9M12938"); ttq.page();',
    isEnabled: false,
  },
];

export const initialStaff: StaffMember[] = [
  {
    id: 'st1',
    name: 'Dhrubo Duti Biswas',
    email: 'dhrubo@shuddhademo.com',
    role: 'Owner (Super Admin)',
    status: 'active',
    lastLogin: '2026-09-25 21:30',
    createdAt: '2026-01-10',
  },
  {
    id: 'st2',
    name: 'Amina Khatun',
    email: 'amina.ops@shuddhademo.com',
    role: 'Order Manager',
    status: 'active',
    lastLogin: '2026-09-25 19:40',
    createdAt: '2026-03-15',
  },
  {
    id: 'st3',
    name: 'Kamrul Hasan',
    email: 'kamrul.inv@shuddhademo.com',
    role: 'Inventory Manager',
    status: 'active',
    lastLogin: '2026-09-24 16:15',
    createdAt: '2026-04-02',
  },
];

export const initialRoles: RolePermission[] = [
  {
    id: 'r1',
    name: 'Owner',
    description: 'Full administrative access across all store and staff features.',
    permissions: [
      'PRODUCTS_VIEW', 'PRODUCTS_CREATE', 'PRODUCTS_EDIT', 'PRODUCTS_ARCHIVE',
      'INVENTORY_VIEW', 'INVENTORY_ADJUST',
      'ORDERS_VIEW', 'ORDERS_EDIT', 'ORDERS_STATUS_CHANGE', 'ORDERS_CANCEL',
      'CATEGORIES_VIEW', 'CATEGORIES_MANAGE',
      'BANNER_VIEW', 'BANNER_MANAGE',
      'REVIEWS_VIEW', 'REVIEWS_MANAGE',
      'STAFF_VIEW', 'STAFF_MANAGE',
      'SETTINGS_VIEW', 'SETTINGS_MANAGE',
    ],
  },
  {
    id: 'r2',
    name: 'Order Manager',
    description: 'Can process, confirm, and manage customer orders and courier checks.',
    permissions: [
      'ORDERS_VIEW', 'ORDERS_EDIT', 'ORDERS_STATUS_CHANGE',
      'PRODUCTS_VIEW', 'INVENTORY_VIEW',
    ],
  },
  {
    id: 'r3',
    name: 'Inventory Manager',
    description: 'Manages catalog stock, product batches and category structures.',
    permissions: [
      'PRODUCTS_VIEW', 'PRODUCTS_CREATE', 'PRODUCTS_EDIT',
      'INVENTORY_VIEW', 'INVENTORY_ADJUST',
      'CATEGORIES_VIEW', 'CATEGORIES_MANAGE',
    ],
  },
  {
    id: 'r4',
    name: 'Marketing Manager',
    description: 'Manages storefront promotional banners, popups, reviews and coupons.',
    permissions: [
      'BANNER_VIEW', 'BANNER_MANAGE',
      'REVIEWS_VIEW', 'REVIEWS_MANAGE',
      'PRODUCTS_VIEW', 'CATEGORIES_VIEW',
    ],
  },
];

export const initialActivityLogs: ActivityLogItem[] = [
  {
    id: 'log1',
    timestamp: '2026-09-25 18:42:15',
    user: 'Customer (Tanzirul)',
    action: 'Order Placed',
    area: 'Orders',
    entity: 'Order #SH-84921',
    details: 'New order placed for Gawa Ghee 1kg and Deshi Mustard Oil 2L (Total: ৳2,530)',
  },
  {
    id: 'log2',
    timestamp: '2026-09-25 17:15:00',
    user: 'Dhrubo Duti Biswas',
    action: 'Price Adjusted',
    area: 'Products',
    entity: 'Gawa Ghee 1kg (SH-GH-01)',
    details: 'Updated promotional price from ৳2,050 to ৳1,990',
  },
  {
    id: 'log3',
    timestamp: '2026-09-25 15:22:40',
    user: 'Amina Khatun',
    action: 'Status Updated',
    area: 'Orders',
    entity: 'Order #SH-84920',
    details: 'Changed status from Pending to Confirmed following bKash payment verification',
  },
  {
    id: 'log4',
    timestamp: '2026-09-25 14:05:10',
    user: 'Kamrul Hasan',
    action: 'Stock Received',
    area: 'Inventory',
    entity: 'Sundarban Wild Honey 1kg',
    details: 'Added +10 units from fresh mangrove honey harvest batch',
  },
  {
    id: 'log5',
    timestamp: '2026-09-24 19:30:20',
    user: 'Dhrubo Duti Biswas',
    action: 'Banner Updated',
    area: 'Banners',
    entity: 'Hero Main Banner',
    details: 'Saved new promotional headline and seasonal farm banner visual',
  },
];

export const initialMediaAssets: MediaAsset[] = [
  {
    id: 'm1',
    name: 'gawa-ghee.jpg',
    url: '/demo-assets/ecommerce/gawa-ghee.jpg',
    dimensions: '1024 x 1024',
    fileSize: '671 KB',
    fileType: 'image/jpeg',
    altText: 'Pure cow gawa ghee 1kg tin with ribbon spice box',
    usageCount: 4,
    uploadedAt: '2026-09-20',
  },
  {
    id: 'm2',
    name: 'ghee-bowl.jpg',
    url: '/demo-assets/ecommerce/ghee-bowl.jpg',
    dimensions: '1024 x 1024',
    fileSize: '509 KB',
    fileType: 'image/jpeg',
    altText: 'Golden yellow granular ghee in ceramic bowl with spoon',
    usageCount: 2,
    uploadedAt: '2026-09-20',
  },
  {
    id: 'm3',
    name: 'sundarban-honey.jpg',
    url: '/demo-assets/ecommerce/sundarban-honey.jpg',
    dimensions: '1024 x 1024',
    fileSize: '758 KB',
    fileType: 'image/jpeg',
    altText: 'Raw wild Sundarban honey jar with dripping honey spoon',
    usageCount: 3,
    uploadedAt: '2026-09-21',
  },
  {
    id: 'm4',
    name: 'black-seed-honey.jpg',
    url: '/demo-assets/ecommerce/black-seed-honey.jpg',
    dimensions: '1024 x 1024',
    fileSize: '608 KB',
    fileType: 'image/jpeg',
    altText: 'Black seed Kalonji floral honey jar with flower',
    usageCount: 2,
    uploadedAt: '2026-09-21',
  },
  {
    id: 'm5',
    name: 'mustard-oil.jpg',
    url: '/demo-assets/ecommerce/mustard-oil.jpg',
    dimensions: '1024 x 1024',
    fileSize: '633 KB',
    fileType: 'image/jpeg',
    altText: 'Cold pressed deshi mustard oil 2 liter bottle',
    usageCount: 3,
    uploadedAt: '2026-09-22',
  },
  {
    id: 'm6',
    name: 'ajwa-dates.jpg',
    url: '/demo-assets/ecommerce/ajwa-dates.jpg',
    dimensions: '1024 x 1024',
    fileSize: '749 KB',
    fileType: 'image/jpeg',
    altText: 'Luxury box of Saudi Ajwa and Medjool dates',
    usageCount: 3,
    uploadedAt: '2026-09-22',
  },
  {
    id: 'm7',
    name: 'turmeric-spices.jpg',
    url: '/demo-assets/ecommerce/turmeric-spices.jpg',
    dimensions: '1024 x 1024',
    fileSize: '632 KB',
    fileType: 'image/jpeg',
    altText: 'Organic turmeric and red dried chilies in jars',
    usageCount: 3,
    uploadedAt: '2026-09-23',
  },
  {
    id: 'm8',
    name: 'nuts-seeds.jpg',
    url: '/demo-assets/ecommerce/nuts-seeds.jpg',
    dimensions: '1024 x 1024',
    fileSize: '762 KB',
    fileType: 'image/jpeg',
    altText: 'Almonds, cashews and chia seeds in jars',
    usageCount: 3,
    uploadedAt: '2026-09-23',
  },
  {
    id: 'm9',
    name: 'hero-banner.jpg',
    url: '/demo-assets/ecommerce/hero-banner.jpg',
    dimensions: '1792 x 1024',
    fileSize: '816 KB',
    fileType: 'image/jpeg',
    altText: 'Farm fresh harvest hero banner with ghee, honey, mustard oil',
    usageCount: 2,
    uploadedAt: '2026-09-24',
  },
  {
    id: 'm10',
    name: 'mid-banner.jpg',
    url: '/demo-assets/ecommerce/mid-banner.jpg',
    dimensions: '1792 x 1024',
    fileSize: '634 KB',
    fileType: 'image/jpeg',
    altText: 'Panoramic pantry goods collection on white table',
    usageCount: 3,
    uploadedAt: '2026-09-24',
  },
];
