import {
  Product,
  Category,
  Coupon,
  Review,
  ComboBundle,
  BannerSlide,
  PopupConfig,
  StaffMember,
  RolePermissions,
  ActivityLogItem,
  IntegrationItem,
  StoreSettings,
  Order,
} from '../_types';

export const initialSettings: StoreSettings = {
  brandName: 'WonderSprout',
  tagline: 'Inspiring Young Minds Through Playful Learning',
  supportPhone: '+1 (800) 482-9768',
  supportEmail: 'hello@wondersprout.store',
  address: '742 Evergreen Play Way, Suite 100, Austin, TX 78701',
  currency: 'USD',
  currencySymbol: '$',
  freeShippingThreshold: 50,
  announcementEnabled: true,
  announcementText:
    '🌟 Back to School Special: Use code SPROUT20 for 20% off all Montessori learning kits! Free nationwide shipping over $50.',
  faviconText: '🌱',
  browserTabTitle: 'WonderSprout | Educational Toys & Montessori Learning Tools',
};

export const initialCategories: Category[] = [
  {
    id: 'cat-montessori',
    slug: 'montessori-learning',
    name: 'Montessori & Early Learning',
    description: 'Self-guided exploratory toys designed for natural fine-motor development.',
    image: '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
    productCount: 4,
    isVisible: true,
    displayOrder: 1,
  },
  {
    id: 'cat-stem',
    slug: 'stem-construction',
    name: 'STEM & Construction',
    description: 'Hands-on gear builders, robotics, astronomy, and physics discovery tools.',
    image: '/demo-assets/ecommerce/demo-04/stem-robot.jpg',
    productCount: 3,
    isVisible: true,
    displayOrder: 2,
  },
  {
    id: 'cat-puzzles',
    slug: 'puzzles-sorting',
    name: 'Puzzles & Shape Sorters',
    description: 'Cognitive shape sorters, wooden animal tangrams, and geometry towers.',
    image: '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
    productCount: 3,
    isVisible: true,
    displayOrder: 3,
  },
  {
    id: 'cat-creative',
    slug: 'creative-arts',
    name: 'Creative Sensory & Clay',
    description: 'Non-toxic organic sculpting dough, modeling kits, and tactile expression sets.',
    image: '/demo-assets/ecommerce/demo-04/modeling-clay.jpg',
    productCount: 2,
    isVisible: true,
    displayOrder: 4,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-01',
    slug: 'abacus-motor-skill-board',
    title: 'Abacus And Motor Skill Counting Board',
    category: 'Montessori & Early Learning',
    ageRange: '3-4 Years',
    material: 'Natural Beechwood',
    type: 'Educational Toy',
    basePrice: 56.55,
    compareAtPrice: 69.0,
    rating: 4.9,
    reviewCount: 48,
    stock: 24,
    status: 'Active',
    badge: 'OFF 18%',
    primaryImage: '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
      '/demo-assets/ecommerce/demo-04/number-cubes.jpg',
      '/demo-assets/ecommerce/demo-04/about-kids.jpg',
    ],
    isFeatured: true,
    isNewArrival: true,
    bestSeller: true,
    shortDescription:
      'Multi-axis counting abacus with vibrant pastel beads, rotating letter and number blocks, and arithmetic calculation sliders.',
    description:
      'Designed in collaboration with early childhood developmental psychologists, this dual-sided Montessori Counting & Motor Skill Board empowers toddlers to physically touch mathematical concepts. Ten stainless steel rows house smooth water-painted beechwood beads, while rotating blocks showcase complete alphabets and foundational digits. Tested to strict ASTM F963 safety standards.',
    educationalBenefits: [
      'Bilateral hand-eye coordination',
      'Early arithmetic visualization & number grouping',
      'Letter recognition and sensory tactile feedback',
      'Sustainably sourced certified beechwood',
    ],
    specs: {
      Dimensions: '34cm x 26cm x 8cm',
      Weight: '1.45 kg',
      Safety: 'EN71 & ASTM F963 Certified non-toxic finish',
      RecommendedAge: '2.5 to 6 Years',
    },
    variants: [
      {
        id: 'var-01-a',
        name: 'Standard Beechwood (3-4 Years)',
        sku: 'WS-ABA-34-WOD',
        price: 56.55,
        compareAtPrice: 69.0,
        inventory: 24,
        attributes: { Age: '3-4 Years', Material: 'Wood', Type: 'Number' },
      },
      {
        id: 'var-01-b',
        name: 'Preschool Master Edition (4-6 Years)',
        sku: 'WS-ABA-46-MST',
        price: 64.0,
        compareAtPrice: 78.0,
        inventory: 16,
        attributes: { Age: '4-6 Years', Material: 'Wood', Type: 'Puzzle' },
      },
    ],
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'prod-02',
    slug: 'rainbow-geometry-stacking-tower',
    title: 'Rainbow Geometry Stacking Ring Tower',
    category: 'Puzzles & Shape Sorters',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Puzzles',
    basePrice: 28.0,
    compareAtPrice: 35.0,
    rating: 4.8,
    reviewCount: 36,
    stock: 42,
    status: 'Active',
    badge: 'OFF 20%',
    primaryImage: '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/shape-cube.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
      '/demo-assets/ecommerce/demo-04/shape-cube.jpg',
    ],
    isFeatured: true,
    isNewArrival: true,
    bestSeller: false,
    shortDescription:
      'Classic Montessori stacking pyramid featuring seven smooth pastel graduated rings topped by a solid wooden sphere.',
    description:
      'A nursery essential that grows with your toddler. Starting from grasping and mouthing smooth curves, toddlers quickly discover spatial relativity, balance principles, and color graduation from warm coral to gentle lilac. Each ring is individually sanded to a velvety soft-touch texture.',
    educationalBenefits: [
      'Spatial graduation & size discrimination',
      'Color spectrum recognition',
      'Pincer grasp dexterity training',
    ],
    specs: {
      Dimensions: '12cm diameter x 24cm height',
      Weight: '0.68 kg',
      Safety: 'Zero chemical lacquer, organic plant tint',
      RecommendedAge: '18 Months to 4 Years',
    },
    variants: [
      {
        id: 'var-02-a',
        name: 'Pastel Rainbow (2-4 Years)',
        sku: 'WS-RNW-STK-PST',
        price: 28.0,
        compareAtPrice: 35.0,
        inventory: 42,
        attributes: { Age: '2-4 Years', Material: 'Wood', Type: 'Standard' },
      },
    ],
    createdAt: '2026-08-18T11:30:00Z',
  },
  {
    id: 'prod-03',
    slug: 'montessori-busy-board-house',
    title: 'Montessori Wooden Busy Board Activity House',
    category: 'Montessori & Early Learning',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Activity Board',
    basePrice: 78.5,
    compareAtPrice: 95.0,
    rating: 5.0,
    reviewCount: 52,
    stock: 18,
    status: 'Active',
    badge: 'Hot',
    primaryImage: '/demo-assets/ecommerce/demo-04/busy-board-house.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/busy-board-house.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/busy-board-house.jpg',
      '/demo-assets/ecommerce/demo-04/classroom.jpg',
    ],
    isFeatured: true,
    isNewArrival: false,
    bestSeller: true,
    shortDescription:
      'Portable playhouse with brass door latches, colorful spinning gears, analog teaching clock, and geometric shape cutouts.',
    description:
      'Inspired by authentic Maria Montessori sensorial pedagogy, this 6-sided activity cottage features real-life fine motor hardware: spring latches, sliding bolts, interlocking gears, and analog clock hands. Includes a convenient wooden carry handle for travels and playdates.',
    educationalBenefits: [
      'Practical everyday life motor mechanics',
      'Curiosity and cause-and-effect exploration',
      'Time-telling foundation with movable clock hands',
    ],
    specs: {
      Dimensions: '28cm x 22cm x 30cm',
      Weight: '2.3 kg',
      Safety: 'Rounded chamfered corners, secured hardware',
      RecommendedAge: '2 to 5 Years',
    },
    variants: [
      {
        id: 'var-03-a',
        name: 'Deluxe Activity House',
        sku: 'WS-BSY-HSE-DLX',
        price: 78.5,
        compareAtPrice: 95.0,
        inventory: 18,
        attributes: { Age: '2-5 Years', Material: 'Wood', Type: 'House' },
      },
    ],
    createdAt: '2026-08-20T09:15:00Z',
  },
  {
    id: 'prod-04',
    slug: 'junior-stem-robot-builder',
    title: 'Science Fiction Robo & STEM Builder',
    category: 'STEM & Construction',
    ageRange: '4-6 Years',
    material: 'Beechwood & Non-Toxic ABS',
    type: 'STEM Kit',
    basePrice: 42.0,
    compareAtPrice: 52.0,
    rating: 4.9,
    reviewCount: 29,
    stock: 31,
    status: 'Active',
    badge: 'OFF 20%',
    primaryImage: '/demo-assets/ecommerce/demo-04/stem-robot.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/stem-robot.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/stem-robot.jpg',
      '/demo-assets/ecommerce/demo-04/about-kids.jpg',
    ],
    isFeatured: true,
    isNewArrival: true,
    bestSeller: true,
    shortDescription:
      'Friendly wooden learning robot equipped with rotating mechanical cogs, antenna toggles, and posable articulating limbs.',
    description:
      'Introduce kindergarteners to mechanical kinematics early! Turning the main chest gear sets the upper dials and belly mechanism into synchronized motion. Fully movable magnetic arms and springy antennae make this friendly robot a favorite bedtime storyteller and engineering partner.',
    educationalBenefits: [
      'Kinematic gear chain comprehension',
      'Spatial reasoning and creative roleplay',
      'Fine-motor finger dexterity',
    ],
    specs: {
      Dimensions: '22cm x 14cm x 8cm',
      Weight: '0.75 kg',
      Safety: 'Water-based non-toxic lacquer',
      RecommendedAge: '3.5 to 8 Years',
    },
    variants: [
      {
        id: 'var-04-a',
        name: 'Cobalt Blue Robo',
        sku: 'WS-RBO-BLU-01',
        price: 42.0,
        compareAtPrice: 52.0,
        inventory: 31,
        attributes: { Age: '4-6 Years', Material: 'Wood', Type: 'Robot' },
      },
    ],
    createdAt: '2026-08-22T14:40:00Z',
  },
  {
    id: 'prod-05',
    slug: 'number-cubes-math-blocks',
    title: 'Montessori Number Cubes & Counting Blocks',
    category: 'Montessori & Early Learning',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Educational Toy',
    basePrice: 34.0,
    compareAtPrice: 40.0,
    rating: 4.7,
    reviewCount: 22,
    stock: 45,
    status: 'Active',
    badge: 'Popular',
    primaryImage: '/demo-assets/ecommerce/demo-04/number-cubes.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/number-cubes.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/number-cubes.jpg',
      '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
    ],
    isFeatured: true,
    isNewArrival: false,
    bestSeller: false,
    shortDescription:
      'Set of 36 smooth beechwood math cubes in soothing pastel tones with engraved numbers from 0 to 100.',
    description:
      'Math made tangible. Toddlers stack, sort by color shades, count sequences, and learn addition and subtraction visually. Made from solid European beechwood with rounded safety edges.',
    educationalBenefits: [
      'Concrete arithmetic understanding',
      'Sequence ordering and pattern recognition',
      'Tactile weight and balance intuition',
    ],
    specs: {
      Dimensions: '4cm x 4cm per block (36 pieces)',
      Weight: '1.1 kg',
      Safety: 'Child-safe vegetable oil seal',
      RecommendedAge: '2 to 7 Years',
    },
    variants: [
      {
        id: 'var-05-a',
        name: 'Pastel Counting Set (36 Pcs)',
        sku: 'WS-MTH-CUB-36',
        price: 34.0,
        compareAtPrice: 40.0,
        inventory: 45,
        attributes: { Age: '2-4 Years', Material: 'Wood', Type: 'Math' },
      },
    ],
    createdAt: '2026-08-25T16:20:00Z',
  },
  {
    id: 'prod-06',
    slug: 'multi-color-organic-clay',
    title: 'Multi-Color Organic Sculpting Clay & Dough',
    category: 'Creative Sensory & Clay',
    ageRange: '2-4 Years',
    material: 'Organic Wheat Flour & Food Dyes',
    type: 'Creative Kit',
    basePrice: 24.0,
    compareAtPrice: 30.0,
    rating: 4.9,
    reviewCount: 41,
    stock: 50,
    status: 'Active',
    badge: 'OFF 20%',
    primaryImage: '/demo-assets/ecommerce/demo-04/modeling-clay.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/modeling-clay.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/modeling-clay.jpg',
      '/demo-assets/ecommerce/demo-04/about-kids.jpg',
    ],
    isFeatured: true,
    isNewArrival: true,
    bestSeller: true,
    shortDescription:
      'All-natural, ultra-soft non-toxic modeling clay kit with rocket cutters, star presses, and wooden roller.',
    description:
      'Crafted from certified organic food-grade ingredients and natural plant pigments. Soft and never crumbly, this dough retains moisture in airtight bamboo pots and smells gently of organic vanilla. Perfect for sensory relaxation, creative sculpting, and tactile discovery.',
    educationalBenefits: [
      'Sensory therapy and tactile regulation',
      'Hand and finger muscle strength conditioning',
      'Imaginative open-ended artistic creation',
    ],
    specs: {
      Contents: '6 x 120g Clay Jars + 4 Wooden Cutters + 1 Mini Roller',
      Ingredients: 'Organic flour, sea salt, cream of tartar, vegetable dyes',
      Safety: '100% Edible-grade, allergen tested',
      RecommendedAge: '18 Months+',
    },
    variants: [
      {
        id: 'var-06-a',
        name: 'Cosmic Colors Set (6 Jars)',
        sku: 'WS-CLY-CSM-06',
        price: 24.0,
        compareAtPrice: 30.0,
        inventory: 50,
        attributes: { Age: '2-4 Years', Material: 'Organic', Type: 'Clay' },
      },
    ],
    createdAt: '2026-08-27T12:00:00Z',
  },
  {
    id: 'prod-07',
    slug: 'wooden-shape-sorting-cube',
    title: 'Montessori Wooden Shape Sorting Cube',
    category: 'Puzzles & Shape Sorters',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Shape Sorter',
    basePrice: 32.0,
    compareAtPrice: 38.0,
    rating: 4.8,
    reviewCount: 30,
    stock: 28,
    status: 'Active',
    badge: 'Popular',
    primaryImage: '/demo-assets/ecommerce/demo-04/shape-cube.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/shape-cube.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/shape-cube.jpg',
      '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
    ],
    isFeatured: false,
    isNewArrival: false,
    bestSeller: true,
    shortDescription:
      'Sturdy natural pine and beechwood cube with 12 distinct precision-carved geometric slots and colored solid blocks.',
    description:
      'The quintessential early problem-solving puzzle. Features a slide-open top lid with damping groove so small fingers are never pinched. Helps toddlers test hypotheses through trial, angle rotation, and auditory drop confirmation.',
    educationalBenefits: [
      'Visual spatial perception',
      'Shape discrimination & geometry basics',
      'Problem-solving perseverance',
    ],
    specs: {
      Dimensions: '16cm x 16cm x 16cm',
      Weight: '0.95 kg',
      Safety: 'Waterborne non-toxic paint',
      RecommendedAge: '18 Months to 4 Years',
    },
    variants: [
      {
        id: 'var-07-a',
        name: 'Natural Pine & 12 Shapes',
        sku: 'WS-SHP-SRT-12',
        price: 32.0,
        compareAtPrice: 38.0,
        inventory: 28,
        attributes: { Age: '2-4 Years', Material: 'Wood', Type: 'Cube' },
      },
    ],
    createdAt: '2026-08-29T10:15:00Z',
  },
  {
    id: 'prod-08',
    slug: 'wooden-pounding-peg-bench',
    title: 'Wooden Peg Pounding Bench & Mallet',
    category: 'Montessori & Early Learning',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Motor Toy',
    basePrice: 29.5,
    compareAtPrice: 36.0,
    rating: 4.7,
    reviewCount: 25,
    stock: 35,
    status: 'Active',
    badge: 'New',
    primaryImage: '/demo-assets/ecommerce/demo-04/pounding-bench.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/pounding-bench.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/pounding-bench.jpg',
      '/demo-assets/ecommerce/demo-04/classroom.jpg',
    ],
    isFeatured: false,
    isNewArrival: true,
    bestSeller: false,
    shortDescription:
      'Reversible wooden bench with 8 colorful rainbow pegs and an ergonomic, weighted toddler pounding mallet.',
    description:
      'Designed for safe energy channeling and physical grip coordination. As each peg is tapped through the durable silicone grip collars, flip the bench over and begin again for endless joyful repetition.',
    educationalBenefits: [
      'Gross-motor arm strength & targeting accuracy',
      'Healthy emotional energy release',
      'Cause and effect sensory feedback',
    ],
    specs: {
      Dimensions: '26cm x 14cm x 12cm',
      Weight: '0.85 kg',
      Safety: 'Smooth rounded edges, impact-absorbing rings',
      RecommendedAge: '18 Months to 4 Years',
    },
    variants: [
      {
        id: 'var-08-a',
        name: 'Rainbow 8-Peg Bench',
        sku: 'WS-PND-BCH-08',
        price: 29.5,
        compareAtPrice: 36.0,
        inventory: 35,
        attributes: { Age: '2-4 Years', Material: 'Wood', Type: 'Bench' },
      },
    ],
    createdAt: '2026-09-01T15:20:00Z',
  },
  {
    id: 'prod-09',
    slug: 'animal-jigsaw-tangram-puzzle',
    title: 'Animal Jigsaw & Tangram Puzzle Tray',
    category: 'Puzzles & Shape Sorters',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Puzzles',
    basePrice: 26.0,
    compareAtPrice: 32.0,
    rating: 4.9,
    reviewCount: 38,
    stock: 40,
    status: 'Active',
    badge: 'OFF 18%',
    primaryImage: '/demo-assets/ecommerce/demo-04/animal-puzzle.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/animal-puzzle.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/animal-puzzle.jpg',
      '/demo-assets/ecommerce/demo-04/about-kids.jpg',
    ],
    isFeatured: true,
    isNewArrival: false,
    bestSeller: true,
    shortDescription:
      'Chunky wooden animal silhouette puzzle featuring elephant, lion, songbird, and sea turtle pieces in a birch tray.',
    description:
      'Thick, freestanding animal blocks that double as puzzle inserts and miniature figurine play pals. Each animal features soft smiling expressions and curved contours crafted specifically for little hands.',
    educationalBenefits: [
      'Animal identification and zoological curiosity',
      'Pincer grasp orientation control',
      'Storytelling and language enrichment',
    ],
    specs: {
      Dimensions: '24cm x 24cm x 2cm',
      Weight: '0.62 kg',
      Safety: 'Natural organic vegetable oil seal',
      RecommendedAge: '18 Months to 5 Years',
    },
    variants: [
      {
        id: 'var-09-a',
        name: 'Safari & Garden Friends',
        sku: 'WS-ANM-PZL-04',
        price: 26.0,
        compareAtPrice: 32.0,
        inventory: 40,
        attributes: { Age: '2-4 Years', Material: 'Wood', Type: 'Puzzle' },
      },
    ],
    createdAt: '2026-09-03T11:00:00Z',
  },
  {
    id: 'prod-10',
    slug: 'solar-system-orrery-planetarium',
    title: 'Solar System Planetarium Discovery Orrery',
    category: 'STEM & Construction',
    ageRange: '6+ Years',
    material: 'Solid Walnut & Brass Gears',
    type: 'STEM Kit',
    basePrice: 89.0,
    compareAtPrice: 115.0,
    rating: 5.0,
    reviewCount: 44,
    stock: 15,
    status: 'Active',
    badge: 'Hot',
    primaryImage: '/demo-assets/ecommerce/demo-04/solar-orrery.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/solar-orrery.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/solar-orrery.jpg',
      '/demo-assets/ecommerce/demo-04/stem-robot.jpg',
    ],
    isFeatured: true,
    isNewArrival: true,
    bestSeller: true,
    shortDescription:
      'Handcrafted mechanical wooden orrery model with 8 rotating hand-painted planets orbiting a central brass sun sphere.',
    description:
      'A true family heirloom and STEM centerpiece. Turn the smooth solid walnut crank at the base to watch Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune rotate around the Sun at mechanically proportional speeds. Includes astronomy handbook with planetary facts.',
    educationalBenefits: [
      'Astronomy & planetary orbit dynamics',
      'Mechanical clockwork gear ratios',
      'Curiosity for space science and physics',
    ],
    specs: {
      Dimensions: '32cm diameter x 36cm height',
      Weight: '2.8 kg',
      Materials: 'Hand-turned walnut, polished brass, non-toxic artist acrylics',
      RecommendedAge: '5 Years to Adult',
    },
    variants: [
      {
        id: 'var-10-a',
        name: 'Grand Orrery with Star Map',
        sku: 'WS-SLR-ORY-MST',
        price: 89.0,
        compareAtPrice: 115.0,
        inventory: 15,
        attributes: { Age: '6+ Years', Material: 'Wood', Type: 'STEM' },
      },
    ],
    createdAt: '2026-09-05T08:30:00Z',
  },
  {
    id: 'prod-11',
    slug: 'sensory-explorer-activity-pod',
    title: 'Sensory Explorer Multi-Activity Center',
    category: 'Montessori & Early Learning',
    ageRange: '2-4 Years',
    material: 'Natural Beechwood',
    type: 'Activity Board',
    basePrice: 65.0,
    compareAtPrice: 82.0,
    rating: 4.8,
    reviewCount: 19,
    stock: 22,
    status: 'Active',
    badge: 'New',
    primaryImage: '/demo-assets/ecommerce/demo-04/busy-board-house.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/busy-board-house.jpg',
      '/demo-assets/ecommerce/demo-04/number-cubes.jpg',
    ],
    isFeatured: false,
    isNewArrival: true,
    bestSeller: false,
    shortDescription:
      'Montessori tactile cube loaded with chime bells, spinning sensory beads, lock latches, and sliding discovery maze.',
    description:
      'Engages young toddlers through tactile tactile exploration, auditory bell feedback, and visual gear tracking. Built from heavy-duty birch ply and smooth sanded solid beech.',
    educationalBenefits: [
      'Auditory and tactile sensory integration',
      'Rotational wrist movement dexterity',
      'Independent calm focus development',
    ],
    specs: {
      Dimensions: '20cm x 20cm x 20cm',
      Weight: '1.6 kg',
      Safety: 'Lead-free brass, certified child-safe lacquer',
      RecommendedAge: '1 to 4 Years',
    },
    variants: [
      {
        id: 'var-11-a',
        name: 'Sensory Explorer Cube',
        sku: 'WS-SNS-POD-01',
        price: 65.0,
        compareAtPrice: 82.0,
        inventory: 22,
        attributes: { Age: '2-4 Years', Material: 'Wood', Type: 'Activity' },
      },
    ],
    createdAt: '2026-09-07T13:45:00Z',
  },
  {
    id: 'prod-12',
    slug: 'montessori-balance-counting-tree',
    title: 'Woodland Counting & Balance Tree Game',
    category: 'Puzzles & Shape Sorters',
    ageRange: '4-6 Years',
    material: 'Natural Beechwood',
    type: 'Educational Toy',
    basePrice: 38.0,
    compareAtPrice: 48.0,
    rating: 4.9,
    reviewCount: 27,
    stock: 26,
    status: 'Active',
    badge: 'OFF 20%',
    primaryImage: '/demo-assets/ecommerce/demo-04/animal-puzzle.jpg',
    secondaryImage: '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
    galleryImages: [
      '/demo-assets/ecommerce/demo-04/animal-puzzle.jpg',
      '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
    ],
    isFeatured: false,
    isNewArrival: false,
    bestSeller: true,
    shortDescription:
      'Interactive wooden balancing tree where kids place songbirds and apples without toppling the canopy.',
    description:
      'Teaches delicate equilibrium and physics intuition. Children take turns rolling a wooden dice and placing birds or weighted fruits onto numbered tree branches, learning strategic counterbalancing.',
    educationalBenefits: [
      'Balance, weight estimation, and center-of-mass intuition',
      'Turn-taking and cooperative social play',
      'Fine pincer precision under light tension',
    ],
    specs: {
      Dimensions: '25cm x 28cm x 15cm',
      Weight: '0.88 kg',
      Safety: 'Solid sustainable rubberwood, water paints',
      RecommendedAge: '3.5 to 8 Years',
    },
    variants: [
      {
        id: 'var-12-a',
        name: 'Balance Tree Complete Set',
        sku: 'WS-BLN-TRE-01',
        price: 38.0,
        compareAtPrice: 48.0,
        inventory: 26,
        attributes: { Age: '4-6 Years', Material: 'Wood', Type: 'Game' },
      },
    ],
    createdAt: '2026-09-09T09:00:00Z',
  },
];

export const initialCombos: ComboBundle[] = [
  {
    id: 'combo-01',
    name: 'Toddler Montessori Starter Bundle',
    slug: 'toddler-montessori-starter',
    description:
      'Complete early sensory development kit: Abacus counting board, Rainbow stacking pyramid, and Organic modeling dough.',
    includedProductIds: ['prod-01', 'prod-02', 'prod-06'],
    originalPrice: 108.55,
    discountPercent: 25,
    bundlePrice: 81.41,
    image: '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
    isActive: true,
    badge: 'Save 25%',
  },
  {
    id: 'combo-02',
    name: 'Young Engineer & Physics Discovery Pack',
    slug: 'young-engineer-physics-pack',
    description:
      'STEM exploration package: Sci-Fi Robot builder, Solar Orrery model, and Geometric Shape cube.',
    includedProductIds: ['prod-04', 'prod-10', 'prod-07'],
    originalPrice: 163.0,
    discountPercent: 20,
    bundlePrice: 130.4,
    image: '/demo-assets/ecommerce/demo-04/solar-orrery.jpg',
    isActive: true,
    badge: 'STEM Bundle',
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-01',
    code: 'SPROUT20',
    discountPercent: 20,
    discountType: 'percentage',
    minSpend: 40,
    usageCount: 142,
    maxUsage: 500,
    isActive: true,
    createdAt: '2026-08-01',
    description: '20% off all educational starter kits over $40 spend',
  },
  {
    id: 'coup-02',
    code: 'WELCOME10',
    discountPercent: 10,
    discountType: 'percentage',
    minSpend: 25,
    usageCount: 89,
    maxUsage: 1000,
    isActive: true,
    createdAt: '2026-08-10',
    description: '10% welcome discount for new parent subscribers',
  },
  {
    id: 'coup-03',
    code: 'MONTESSORI15',
    discountPercent: 15,
    discountType: 'percentage',
    minSpend: 50,
    usageCount: 64,
    maxUsage: 300,
    isActive: true,
    createdAt: '2026-08-20',
    description: '15% off classroom activity boards',
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-01',
    productId: 'prod-01',
    productTitle: 'Abacus And Motor Skill Counting Board',
    author: 'Clara Jenkins (Montessori Educator)',
    rating: 5,
    date: '2026-09-12',
    title: 'Remarkable quality, pure joy in our toddler room!',
    content:
      'We introduced the WonderSprout abacus into our toddler classroom two weeks ago. The weight of the wood, the silky finish of the beads, and the rotating letter blocks hold children spellbound. Truly masterclass craftsmanship.',
    isVerified: true,
    isVisible: true,
    city: 'Seattle, WA',
  },
  {
    id: 'rev-02',
    productId: 'prod-01',
    productTitle: 'Abacus And Motor Skill Counting Board',
    author: 'Marcus Vance',
    rating: 5,
    date: '2026-09-08',
    title: 'My 3-year-old counts to 20 effortlessly now',
    content:
      'Unlike plastic toys with blaring noises, this encourages deep concentration. My daughter loves lining up the beads and turning the letters to spell out her name.',
    isVerified: true,
    isVisible: true,
    city: 'Austin, TX',
  },
  {
    id: 'rev-03',
    productId: 'prod-03',
    productTitle: 'Montessori Wooden Busy Board Activity House',
    author: 'Elena Rostova',
    rating: 5,
    date: '2026-09-04',
    title: 'The best investment we made for screen-free play',
    content:
      'This busy cottage kept our twin toddlers happily occupied for hours during a 6-hour family road trip. The brass hardware is sturdy and completely child-safe.',
    isVerified: true,
    isVisible: true,
    city: 'Denver, CO',
  },
  {
    id: 'rev-04',
    productId: 'prod-04',
    productTitle: 'Science Fiction Robo & STEM Builder',
    author: 'David K. Cho',
    rating: 5,
    date: '2026-08-30',
    title: 'Ingenious gear mechanism for little hands',
    content:
      'Our son loves turning the cogs and feeling how one gear drives the entire system. Very sturdy construction, survived multiple drops from the play table without a scratch.',
    isVerified: true,
    isVisible: true,
    city: 'Chicago, IL',
  },
  {
    id: 'rev-05',
    productId: 'prod-10',
    productTitle: 'Solar System Planetarium Discovery Orrery',
    author: 'Dr. Evelyn Howard (Astrophysicist & Mom)',
    rating: 5,
    date: '2026-08-26',
    title: 'Breathtaking mechanical heirloom',
    content:
      'I was astonished by the accuracy of the planetary gear trains. It looks gorgeous on our living room bookshelf and has sparked wonderful bedtime questions about Saturn rings and Earth orbit.',
    isVerified: true,
    isVisible: true,
    city: 'Boston, MA',
  },
];

export const initialBanners: BannerSlide[] = [
  {
    id: 'ban-01',
    title: '20% Flat Off',
    subtitle: 'On Early Learning & Montessori Kits',
    tagline: 'Best Pathway For Smart Learning',
    ctaText: 'Explore Starter Kits',
    ctaLink: '/webapp-demo/ecommerce/demo-04/collection',
    imageDesktop: '/demo-assets/ecommerce/demo-04/hero-banner.jpg',
    imageMobile: '/demo-assets/ecommerce/demo-04/hero-banner.jpg',
    isActive: true,
    displayOrder: 1,
    accentBadge: 'Special Offer',
  },
  {
    id: 'ban-02',
    title: 'Smart Pathways',
    subtitle: 'Handcrafted Wooden Early Education',
    tagline: 'Open Their Creative Wings',
    ctaText: 'Shop New Arrivals',
    ctaLink: '/webapp-demo/ecommerce/demo-04/collection',
    imageDesktop: '/demo-assets/ecommerce/demo-04/hero-banner.jpg',
    imageMobile: '/demo-assets/ecommerce/demo-04/hero-banner.jpg',
    isActive: true,
    displayOrder: 2,
    accentBadge: 'New Montessori',
  },
  {
    id: 'ban-03',
    title: "It's Playtime!",
    subtitle: 'Sensory Wonder For Curious Minds',
    tagline: 'Certified Safe & Sustainable Materials',
    ctaText: 'Discover All Toys',
    ctaLink: '/webapp-demo/ecommerce/demo-04/collection',
    imageDesktop: '/demo-assets/ecommerce/demo-04/hero-banner.jpg',
    imageMobile: '/demo-assets/ecommerce/demo-04/hero-banner.jpg',
    isActive: true,
    displayOrder: 3,
    accentBadge: 'Heirloom Quality',
  },
];

export const initialPopup: PopupConfig = {
  isEnabled: true,
  badge: 'WELCOME GIFT',
  title: 'Get 20% Off Your First Playful Order',
  description:
    'Join our WonderSprout family today! Get free early childhood learning tips and save 20% on all wooden educational toys.',
  couponCode: 'SPROUT20',
  buttonText: 'Claim 20% Voucher',
  buttonLink: '/webapp-demo/ecommerce/demo-04/collection',
  image: '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
};

export const initialOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'WS-2026-8941',
    date: '2026-09-26T14:32:00Z',
    customerName: 'Sarah Montgomery',
    customerEmail: 'sarah.m@example.com',
    phone: '+1 (512) 839-4401',
    address: '1428 Oak Crest Lane',
    city: 'Austin, TX',
    postalCode: '78704',
    items: [
      {
        productId: 'prod-01',
        variantId: 'var-01-a',
        title: 'Abacus And Motor Skill Counting Board',
        variantName: 'Standard Beechwood',
        price: 56.55,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-04/abacus-board.jpg',
      },
      {
        productId: 'prod-02',
        variantId: 'var-02-a',
        title: 'Rainbow Geometry Stacking Ring Tower',
        variantName: 'Pastel Rainbow',
        price: 28.0,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-04/rainbow-tower.jpg',
      },
    ],
    subtotal: 84.55,
    discount: 16.91,
    couponCode: 'SPROUT20',
    shippingFee: 0,
    total: 67.64,
    paymentMethod: 'Credit Card (Apple Pay)',
    status: 'Confirmed',
    statusHistory: [
      { status: 'Pending', timestamp: '2026-09-26T14:32:00Z' },
      { status: 'Confirmed', timestamp: '2026-09-26T14:45:00Z', note: 'Payment captured successfully' },
    ],
    notes: 'Gift wrapping requested with Happy 3rd Birthday card.',
    fraudRisk: 'Low',
    fraudScore: 8,
  },
  {
    id: 'ord-102',
    orderNumber: 'WS-2026-8940',
    date: '2026-09-25T11:15:00Z',
    customerName: 'Jonathan Davis',
    customerEmail: 'j.davis@example.org',
    phone: '+1 (206) 555-0192',
    address: '730 Pinehurst Way',
    city: 'Seattle, WA',
    postalCode: '98103',
    items: [
      {
        productId: 'prod-03',
        variantId: 'var-03-a',
        title: 'Montessori Wooden Busy Board Activity House',
        variantName: 'Deluxe Activity House',
        price: 78.5,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-04/busy-board-house.jpg',
      },
    ],
    subtotal: 78.5,
    discount: 0,
    shippingFee: 0,
    total: 78.5,
    paymentMethod: 'Credit Card',
    status: 'Shipped',
    statusHistory: [
      { status: 'Pending', timestamp: '2026-09-25T11:15:00Z' },
      { status: 'Confirmed', timestamp: '2026-09-25T11:20:00Z' },
      { status: 'Packed', timestamp: '2026-09-25T15:00:00Z' },
      { status: 'Shipped', timestamp: '2026-09-26T09:00:00Z', note: 'Tracking: 1Z9999999999999999' },
    ],
    fraudRisk: 'Low',
    fraudScore: 12,
  },
  {
    id: 'ord-103',
    orderNumber: 'WS-2026-8939',
    date: '2026-09-24T18:40:00Z',
    customerName: 'Maya Lin',
    customerEmail: 'mayalin.creative@example.com',
    phone: '+1 (415) 802-9912',
    address: '450 Sutter St, Apt 4B',
    city: 'San Francisco, CA',
    postalCode: '94108',
    items: [
      {
        productId: 'prod-10',
        variantId: 'var-10-a',
        title: 'Solar System Planetarium Discovery Orrery',
        variantName: 'Grand Orrery with Star Map',
        price: 89.0,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-04/solar-orrery.jpg',
      },
      {
        productId: 'prod-06',
        variantId: 'var-06-a',
        title: 'Multi-Color Organic Sculpting Clay & Dough',
        variantName: 'Cosmic Colors Set',
        price: 24.0,
        quantity: 2,
        thumbnail: '/demo-assets/ecommerce/demo-04/modeling-clay.jpg',
      },
    ],
    subtotal: 137.0,
    discount: 27.4,
    couponCode: 'SPROUT20',
    shippingFee: 0,
    total: 109.6,
    paymentMethod: 'Credit Card',
    status: 'Delivered',
    statusHistory: [
      { status: 'Pending', timestamp: '2026-09-24T18:40:00Z' },
      { status: 'Confirmed', timestamp: '2026-09-24T18:42:00Z' },
      { status: 'Packed', timestamp: '2026-09-25T08:00:00Z' },
      { status: 'Shipped', timestamp: '2026-09-25T11:00:00Z' },
      { status: 'Delivered', timestamp: '2026-09-26T16:20:00Z', note: 'Left on porch' },
    ],
    fraudRisk: 'Low',
    fraudScore: 5,
  },
  {
    id: 'ord-104',
    orderNumber: 'WS-2026-8938',
    date: '2026-09-24T10:05:00Z',
    customerName: 'Robert Vance',
    customerEmail: 'rvance@example.net',
    phone: '+1 (312) 441-2098',
    address: '880 N Michigan Ave',
    city: 'Chicago, IL',
    postalCode: '60611',
    items: [
      {
        productId: 'prod-04',
        variantId: 'var-04-a',
        title: 'Science Fiction Robo & STEM Builder',
        variantName: 'Cobalt Blue Robo',
        price: 42.0,
        quantity: 1,
        thumbnail: '/demo-assets/ecommerce/demo-04/stem-robot.jpg',
      },
    ],
    subtotal: 42.0,
    discount: 0,
    shippingFee: 5.0,
    total: 47.0,
    paymentMethod: 'Cash on Delivery',
    status: 'Pending',
    statusHistory: [{ status: 'Pending', timestamp: '2026-09-24T10:05:00Z' }],
    notes: 'Please verify phone before dispatch.',
    fraudRisk: 'Medium',
    fraudScore: 38,
  },
];

export const initialStaff: StaffMember[] = [
  {
    id: 'staff-01',
    name: 'Emily Thornton',
    email: 'emily@wondersprout.store',
    role: 'Owner',
    status: 'Active',
    avatar: '👩‍🏫',
    lastLogin: '2026-09-26T22:15:00Z',
    createdAt: '2026-01-10',
  },
  {
    id: 'staff-02',
    name: 'Julian Mercer',
    email: 'julian.ops@wondersprout.store',
    role: 'Order Manager',
    status: 'Active',
    avatar: '👨‍💼',
    lastLogin: '2026-09-26T21:40:00Z',
    createdAt: '2026-03-15',
  },
  {
    id: 'staff-03',
    name: 'Chloe Zhang',
    email: 'chloe.inv@wondersprout.store',
    role: 'Inventory Manager',
    status: 'Active',
    avatar: '👩‍💻',
    lastLogin: '2026-09-26T18:00:00Z',
    createdAt: '2026-04-01',
  },
  {
    id: 'staff-04',
    name: 'Liam Sterling',
    email: 'liam.mkt@wondersprout.store',
    role: 'Marketing Manager',
    status: 'Active',
    avatar: '👨‍🎨',
    lastLogin: '2026-09-26T19:25:00Z',
    createdAt: '2026-05-12',
  },
];

export const initialRoles: RolePermissions[] = [
  {
    role: 'Owner',
    description: 'Full administrative control over store, finances, staff and configuration.',
    permissions: {
      PRODUCTS_VIEW: true,
      PRODUCTS_CREATE: true,
      PRODUCTS_EDIT: true,
      PRODUCTS_ARCHIVE: true,
      ORDERS_VIEW: true,
      ORDERS_EDIT: true,
      ORDERS_STATUS_CHANGE: true,
      ORDERS_CANCEL: true,
      INVENTORY_VIEW: true,
      INVENTORY_ADJUST: true,
      CATEGORIES_VIEW: true,
      CATEGORIES_MANAGE: true,
      BANNER_VIEW: true,
      BANNER_MANAGE: true,
      REVIEWS_VIEW: true,
      REVIEWS_MANAGE: true,
      STAFF_VIEW: true,
      STAFF_MANAGE: true,
      SETTINGS_VIEW: true,
      SETTINGS_MANAGE: true,
    },
  },
  {
    role: 'Order Manager',
    description: 'Processes fulfillment, updates shipping, and handles customer support.',
    permissions: {
      PRODUCTS_VIEW: true,
      PRODUCTS_CREATE: false,
      PRODUCTS_EDIT: false,
      PRODUCTS_ARCHIVE: false,
      ORDERS_VIEW: true,
      ORDERS_EDIT: true,
      ORDERS_STATUS_CHANGE: true,
      ORDERS_CANCEL: true,
      INVENTORY_VIEW: true,
      INVENTORY_ADJUST: false,
      CATEGORIES_VIEW: true,
      CATEGORIES_MANAGE: false,
      BANNER_VIEW: false,
      BANNER_MANAGE: false,
      REVIEWS_VIEW: true,
      REVIEWS_MANAGE: false,
      STAFF_VIEW: false,
      STAFF_MANAGE: false,
      SETTINGS_VIEW: false,
      SETTINGS_MANAGE: false,
    },
  },
  {
    role: 'Inventory Manager',
    description: 'Monitors stock thresholds, adjusts quantities, and tracks shipments.',
    permissions: {
      PRODUCTS_VIEW: true,
      PRODUCTS_CREATE: true,
      PRODUCTS_EDIT: true,
      PRODUCTS_ARCHIVE: false,
      ORDERS_VIEW: true,
      ORDERS_EDIT: false,
      ORDERS_STATUS_CHANGE: false,
      ORDERS_CANCEL: false,
      INVENTORY_VIEW: true,
      INVENTORY_ADJUST: true,
      CATEGORIES_VIEW: true,
      CATEGORIES_MANAGE: false,
      BANNER_VIEW: false,
      BANNER_MANAGE: false,
      REVIEWS_VIEW: false,
      REVIEWS_MANAGE: false,
      STAFF_VIEW: false,
      STAFF_MANAGE: false,
      SETTINGS_VIEW: false,
      SETTINGS_MANAGE: false,
    },
  },
  {
    role: 'Marketing Manager',
    description: 'Manages promotions, hero carousels, coupons, and customer reviews.',
    permissions: {
      PRODUCTS_VIEW: true,
      PRODUCTS_CREATE: false,
      PRODUCTS_EDIT: true,
      PRODUCTS_ARCHIVE: false,
      ORDERS_VIEW: false,
      ORDERS_EDIT: false,
      ORDERS_STATUS_CHANGE: false,
      ORDERS_CANCEL: false,
      INVENTORY_VIEW: false,
      INVENTORY_ADJUST: false,
      CATEGORIES_VIEW: true,
      CATEGORIES_MANAGE: true,
      BANNER_VIEW: true,
      BANNER_MANAGE: true,
      REVIEWS_VIEW: true,
      REVIEWS_MANAGE: true,
      STAFF_VIEW: false,
      STAFF_MANAGE: false,
      SETTINGS_VIEW: true,
      SETTINGS_MANAGE: false,
    },
  },
];

export const initialIntegrations: IntegrationItem[] = [
  {
    id: 'int-01',
    name: 'Google Tag Manager',
    provider: 'GTM',
    trackingId: 'GTM-WS98402',
    isEnabled: true,
    lastSync: '2026-09-26T22:00:00Z',
    description: 'Ecommerce event tracking (view_item, add_to_cart, purchase)',
  },
  {
    id: 'int-02',
    name: 'Meta Pixel',
    provider: 'Meta',
    trackingId: '98402948219482',
    isEnabled: true,
    lastSync: '2026-09-26T22:00:00Z',
    description: 'Facebook & Instagram catalogue sync & conversion tracking',
  },
  {
    id: 'int-03',
    name: 'TikTok Pixel',
    provider: 'TikTok',
    trackingId: 'TT-WS-840192',
    isEnabled: false,
    lastSync: '2026-09-20T10:00:00Z',
    description: 'Short-form educational toy showcase campaign tracking',
  },
  {
    id: 'int-04',
    name: 'Courier Dispatch Webhook',
    provider: 'Webhook',
    trackingId: 'https://api.courier.demo/v1/wondersprout',
    isEnabled: true,
    lastSync: '2026-09-26T21:45:00Z',
    description: 'Simulated automated shipping label generation',
  },
];

export const initialActivityLog: ActivityLogItem[] = [
  {
    id: 'act-01',
    timestamp: '2026-09-26T21:45:00Z',
    user: 'Emily Thornton (Owner)',
    action: 'Coupon Activated',
    area: 'Coupons',
    entity: 'SPROUT20',
    details: 'Set 20% discount coupon active for fall Montessori campaign.',
  },
  {
    id: 'act-02',
    timestamp: '2026-09-26T18:10:00Z',
    user: 'Julian Mercer (Order Manager)',
    action: 'Order Status Changed',
    area: 'Orders',
    entity: 'WS-2026-8940',
    details: 'Status updated from Packed to Shipped with tracking number.',
  },
  {
    id: 'act-03',
    timestamp: '2026-09-26T15:20:00Z',
    user: 'Chloe Zhang (Inventory Manager)',
    action: 'Stock Replenished',
    area: 'Inventory',
    entity: 'prod-01 (Abacus Board)',
    details: 'Stock increased +10 units to total 24 units on hand.',
  },
  {
    id: 'act-04',
    timestamp: '2026-09-26T14:32:00Z',
    user: 'Storefront Customer',
    action: 'Order Created',
    area: 'Orders',
    entity: 'WS-2026-8941',
    details: 'New order placed by Sarah Montgomery for $67.64 (2 items).',
  },
  {
    id: 'act-05',
    timestamp: '2026-09-26T11:00:00Z',
    user: 'Liam Sterling (Marketing Manager)',
    action: 'Hero Banner Updated',
    area: 'Banners',
    entity: 'Slide 1: Back to School Special',
    details: 'Refreshed slide headline and updated CTA button destination.',
  },
];
